## Season 2 - Sentiment Analysis - Twin Peaks
## Mark Baber
## Load Libraries
library(dplyr)
library(tidytext)
library(tidyverse)
library(tidyr)
library(stringr)
library(readr)

## Season 2
## Import Datasets
s2e1 <- read.csv("s2e1-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e2 <- read.csv("s2e2-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e3 <- read.csv("s2e3-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e4 <- read.csv("s2e4-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e5 <- read.csv("s2e5-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e6 <- read.csv("s2e6-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e7 <- read.csv("s2e7-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e8 <- read.csv("s2e8-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e9 <- read.csv("s2e9-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e10 <- read.csv("s2e10-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e11 <- read.csv("s2e11-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e12 <- read.csv("s2e12-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e13 <- read.csv("s2e13-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e14 <- read.csv("s2e14-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e15 <- read.csv("s2e15-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e16 <- read.csv("s2e16-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e17 <- read.csv("s2e17-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e18 <- read.csv("s2e18-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e19 <- read.csv("s2e19-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e20 <- read.csv("s2e20-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e21 <- read.csv("s2e21-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e22 <- read.csv("s2e22-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
## create a tibble with the Episode ([,1]) & Words ([,2])
tibs2e1 <- tibble(Episode = s2e1[,1], Words = s2e1[,2])
tibs2e2 <- tibble(Episode = s2e2[,1], Words = s2e2[,2])
tibs2e3 <- tibble(Episode = s2e3[,1], Words = s2e3[,2])
tibs2e4 <- tibble(Episode = s2e4[,1], Words = s2e4[,2])
tibs2e5 <- tibble(Episode = s2e5[,1], Words = s2e5[,2])
tibs2e6 <- tibble(Episode = s2e6[,1], Words = s2e6[,2])
tibs2e7 <- tibble(Episode = s2e7[,1], Words = s2e7[,2])
tibs2e8 <- tibble(Episode = s2e8[,1], Words = s2e8[,2])
tibs2e9 <- tibble(Episode = s2e9[,1], Words = s2e9[,2])
tibs2e10 <- tibble(Episode = s2e10[,1], Words = s2e10[,2])
tibs2e11 <- tibble(Episode = s2e11[,1], Words = s2e11[,2])
tibs2e12 <- tibble(Episode = s2e12[,1], Words = s2e12[,2])
tibs2e13 <- tibble(Episode = s2e13[,1], Words = s2e13[,2])
tibs2e14 <- tibble(Episode = s2e14[,1], Words = s2e14[,2])
tibs2e15 <- tibble(Episode = s2e15[,1], Words = s2e15[,2])
tibs2e16 <- tibble(Episode = s2e16[,1], Words = s2e16[,2])
tibs2e17 <- tibble(Episode = s2e17[,1], Words = s2e17[,2])
tibs2e18 <- tibble(Episode = s2e18[,1], Words = s2e18[,2])
tibs2e19 <- tibble(Episode = s2e19[,1], Words = s2e19[,2])
tibs2e20 <- tibble(Episode = s2e20[,1], Words = s2e20[,2])
tibs2e21 <- tibble(Episode = s2e21[,1], Words = s2e21[,2])
tibs2e22 <- tibble(Episode = s2e22[,1], Words = s2e22[,2])

## Unnest words before dictionary
tokenS2E1 <- tibs2e1 %>% unnest_tokens(word, Words)
tokenS2E2 <- tibs2e2 %>% unnest_tokens(word, Words)
tokenS2E3 <- tibs2e3 %>% unnest_tokens(word, Words)
tokenS2E4 <- tibs2e4 %>% unnest_tokens(word, Words)
tokenS2E5 <- tibs2e5 %>% unnest_tokens(word, Words)
tokenS2E6 <- tibs2e6 %>% unnest_tokens(word, Words)
tokenS2E7 <- tibs2e7 %>% unnest_tokens(word, Words)
tokenS2E8 <- tibs2e8 %>% unnest_tokens(word, Words)
tokenS2E9 <- tibs2e9 %>% unnest_tokens(word, Words)
tokenS2E10 <- tibs2e10 %>% unnest_tokens(word, Words)
tokenS2E11 <- tibs2e11 %>% unnest_tokens(word, Words)
tokenS2E12 <- tibs2e12 %>% unnest_tokens(word, Words)
tokenS2E13 <- tibs2e13 %>% unnest_tokens(word, Words)
tokenS2E14 <- tibs2e14 %>% unnest_tokens(word, Words)
tokenS2E15 <- tibs2e15 %>% unnest_tokens(word, Words)
tokenS2E16 <- tibs2e16 %>% unnest_tokens(word, Words)
tokenS2E17 <- tibs2e17 %>% unnest_tokens(word, Words)
tokenS2E18 <- tibs2e18 %>% unnest_tokens(word, Words)
tokenS2E19 <- tibs2e19 %>% unnest_tokens(word, Words)
tokenS2E20 <- tibs2e20 %>% unnest_tokens(word, Words)
tokenS2E21 <- tibs2e21 %>% unnest_tokens(word, Words)
tokenS2E22 <- tibs2e22 %>% unnest_tokens(word, Words)

## afinn
afinns2e1 <- tibs2e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e2 <- tibs2e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e3 <- tibs2e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e4 <- tibs2e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e5 <- tibs2e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e6 <- tibs2e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e7 <- tibs2e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e8 <- tibs2e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e9 <- tibs2e9 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e10 <- tibs2e10 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e11 <- tibs2e11 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e12 <- tibs2e12 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e13 <- tibs2e13 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e14 <- tibs2e14 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e15 <- tibs2e15 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e16 <- tibs2e16 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e17 <- tibs2e17 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e18 <- tibs2e18 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e19 <- tibs2e19 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e20 <- tibs2e20 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e21 <- tibs2e21 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e22 <- tibs2e22 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
## bing
bings2e1 <- tibs2e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e2 <- tibs2e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e3 <- tibs2e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e4 <- tibs2e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e5 <- tibs2e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e6 <- tibs2e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e7 <- tibs2e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e8 <- tibs2e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e9 <- tibs2e9 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e10 <- tibs2e10 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e11 <- tibs2e11 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e12 <- tibs2e12 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e13 <- tibs2e13 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e14 <- tibs2e14 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e15 <- tibs2e15 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e16 <- tibs2e16 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e17 <- tibs2e17 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e18 <- tibs2e18 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e19 <- tibs2e19 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e20 <- tibs2e20 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e21 <- tibs2e21 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e22 <- tibs2e22 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
## Count afinn
countafinn2e1 <- count(afinns2e1, vars = "Episode")
countafinn2e2 <- count(afinns2e2, vars = "Episode")
countafinn2e3 <- count(afinns2e3, vars = "Episode")
countafinn2e4 <- count(afinns2e4, vars = "Episode")
countafinn2e5 <- count(afinns2e5, vars = "Episode")
countafinn2e6 <- count(afinns2e6, vars = "Episode")
countafinn2e7 <- count(afinns2e7, vars = "Episode")
countafinn2e8 <- count(afinns2e8, vars = "Episode")
countafinn2e9 <- count(afinns2e9, vars = "Episode")
countafinn2e10 <- count(afinns2e10, vars = "Episode")
countafinn2e11 <- count(afinns2e11, vars = "Episode")
countafinn2e12 <- count(afinns2e12, vars = "Episode")
countafinn2e13 <- count(afinns2e13, vars = "Episode")
countafinn2e14 <- count(afinns2e14, vars = "Episode")
countafinn2e15 <- count(afinns2e15, vars = "Episode")
countafinn2e16 <- count(afinns2e16, vars = "Episode")
countafinn2e17 <- count(afinns2e17, vars = "Episode")
countafinn2e18 <- count(afinns2e18, vars = "Episode")
countafinn2e19 <- count(afinns2e19, vars = "Episode")
countafinn2e20 <- count(afinns2e20, vars = "Episode")
countafinn2e21 <- count(afinns2e21, vars = "Episode")
countafinn2e22 <- count(afinns2e22, vars = "Episode")
## Count bing
countbings2e1 <- count(bings2e1, vars = "Episode")
countbings2e2 <- count(bings2e2, vars = "Episode")
countbings2e3 <- count(bings2e3, vars = "Episode")
countbings2e4 <- count(bings2e4, vars = "Episode")
countbings2e5 <- count(bings2e5, vars = "Episode")
countbings2e6 <- count(bings2e6, vars = "Episode")
countbings2e7 <- count(bings2e7, vars = "Episode")
countbings2e8 <- count(bings2e8, vars = "Episode")
countbings2e9 <- count(bings2e9, vars = "Episode")
countbings2e10 <- count(bings2e10, vars = "Episode")
countbings2e11 <- count(bings2e11, vars = "Episode")
countbings2e12 <- count(bings2e12, vars = "Episode")
countbings2e13 <- count(bings2e13, vars = "Episode")
countbings2e14 <- count(bings2e14, vars = "Episode")
countbings2e15 <- count(bings2e15, vars = "Episode")
countbings2e16 <- count(bings2e16, vars = "Episode")
countbings2e17 <- count(bings2e17, vars = "Episode")
countbings2e18 <- count(bings2e18, vars = "Episode")
countbings2e19 <- count(bings2e19, vars = "Episode")
countbings2e20 <- count(bings2e20, vars = "Episode")
countbings2e21 <- count(bings2e21, vars = "Episode")
countbings2e22 <- count(bings2e22, vars = "Episode")
## afinn filter positive
positiveafinns2e1 <-  afinns2e1 %>% filter(value >= 0)
positiveafinns2e2 <-  afinns2e2 %>% filter(value >= 0)
positiveafinns2e3 <-  afinns2e3 %>% filter(value >= 0)
positiveafinns2e4 <-  afinns2e4 %>% filter(value >= 0)
positiveafinns2e5 <-  afinns2e5 %>% filter(value >= 0)
positiveafinns2e6 <-  afinns2e6 %>% filter(value >= 0)
positiveafinns2e7 <-  afinns2e7 %>% filter(value >= 0)
positiveafinns2e8 <-  afinns2e8 %>% filter(value >= 0)
positiveafinns2e9 <-  afinns2e9 %>% filter(value >= 0)
positiveafinns2e10 <- afinns2e10 %>% filter(value >= 0)
positiveafinns2e11 <- afinns2e11 %>% filter(value >= 0)
positiveafinns2e12 <- afinns2e12 %>% filter(value >= 0)
positiveafinns2e13 <- afinns2e13 %>% filter(value >= 0)
positiveafinns2e14 <- afinns2e14 %>% filter(value >= 0)
positiveafinns2e15 <- afinns2e15 %>% filter(value >= 0)
positiveafinns2e16 <- afinns2e16 %>% filter(value >= 0)
positiveafinns2e17 <- afinns2e17 %>% filter(value >= 0)
positiveafinns2e18 <- afinns2e18 %>% filter(value >= 0)
positiveafinns2e19 <- afinns2e19 %>% filter(value >= 0)
positiveafinns2e20 <- afinns2e20 %>% filter(value >= 0)
positiveafinns2e21 <- afinns2e21 %>% filter(value >= 0)
positiveafinns2e22 <- afinns2e22 %>% filter(value >= 0)
## bing filter positive bing
positivebings2e1 <-  bings2e1 %>% filter(sentiment == 'positive')
positivebings2e2 <-  bings2e2 %>% filter(sentiment == 'positive')
positivebings2e3 <-  bings2e3 %>% filter(sentiment == 'positive')
positivebings2e4 <-  bings2e4 %>% filter(sentiment == 'positive')
positivebings2e5 <-  bings2e5 %>% filter(sentiment == 'positive')
positivebings2e6 <-  bings2e6 %>% filter(sentiment == 'positive')
positivebings2e7 <-  bings2e7 %>% filter(sentiment == 'positive')
positivebings2e8 <-  bings2e8 %>% filter(sentiment == 'positive')
positivebings2e9 <-  bings2e9 %>% filter(sentiment == 'positive')
positivebings2e10 <- bings2e10 %>% filter(sentiment == 'positive')
positivebings2e11 <- bings2e11 %>% filter(sentiment == 'positive')
positivebings2e12 <- bings2e12 %>% filter(sentiment == 'positive')
positivebings2e13 <- bings2e13 %>% filter(sentiment == 'positive')
positivebings2e14 <- bings2e14 %>% filter(sentiment == 'positive')
positivebings2e15 <- bings2e15 %>% filter(sentiment == 'positive')
positivebings2e16 <- bings2e16 %>% filter(sentiment == 'positive')
positivebings2e17 <- bings2e17 %>% filter(sentiment == 'positive')
positivebings2e18 <- bings2e18 %>% filter(sentiment == 'positive')
positivebings2e19 <- bings2e19 %>% filter(sentiment == 'positive')
positivebings2e20 <- bings2e20 %>% filter(sentiment == 'positive')
positivebings2e21 <- bings2e21 %>% filter(sentiment == 'positive')
positivebings2e22 <- bings2e22 %>% filter(sentiment == 'positive')
## afinn Count Positives
countPAs2e1 <-  count(positiveafinns2e1, vars = "Episode")
countPAs2e2 <-  count(positiveafinns2e2, vars = "Episode")
countPAs2e3 <-  count(positiveafinns2e3, vars = "Episode")
countPAs2e4 <-  count(positiveafinns2e4, vars = "Episode")
countPAs2e5 <-  count(positiveafinns2e5, vars = "Episode")
countPAs2e6 <-  count(positiveafinns2e6, vars = "Episode")
countPAs2e7 <-  count(positiveafinns2e7, vars = "Episode")
countPAs2e8 <-  count(positiveafinns2e8, vars = "Episode")
countPAs2e9 <-  count(positiveafinns2e9, vars = "Episode")
countPAs2e10 <- count(positiveafinns2e10, vars = "Episode")
countPAs2e11 <- count(positiveafinns2e11, vars = "Episode")
countPAs2e12 <- count(positiveafinns2e12, vars = "Episode")
countPAs2e13 <- count(positiveafinns2e13, vars = "Episode")
countPAs2e14 <- count(positiveafinns2e14, vars = "Episode")
countPAs2e15 <- count(positiveafinns2e15, vars = "Episode")
countPAs2e16 <- count(positiveafinns2e16, vars = "Episode")
countPAs2e17 <- count(positiveafinns2e17, vars = "Episode")
countPAs2e18 <- count(positiveafinns2e18, vars = "Episode")
countPAs2e19 <- count(positiveafinns2e19, vars = "Episode")
countPAs2e20 <- count(positiveafinns2e20, vars = "Episode")
countPAs2e21 <- count(positiveafinns2e21, vars = "Episode")
countPAs2e22 <- count(positiveafinns2e22, vars = "Episode")
## bing Count Positives
countPBs2e1 <-  count(positivebings2e1, vars = "Episode")
countPBs2e2 <-  count(positivebings2e2, vars = "Episode")
countPBs2e3 <-  count(positivebings2e3, vars = "Episode")
countPBs2e4 <-  count(positivebings2e4, vars = "Episode")
countPBs2e5 <-  count(positivebings2e5, vars = "Episode")
countPBs2e6 <-  count(positivebings2e6, vars = "Episode")
countPBs2e7 <-  count(positivebings2e7, vars = "Episode")
countPBs2e8 <-  count(positivebings2e8, vars = "Episode")
countPBs2e9 <-  count(positivebings2e9, vars = "Episode")
countPBs2e10 <- count(positivebings2e10, vars = "Episode")
countPBs2e11 <- count(positivebings2e11, vars = "Episode")
countPBs2e12 <- count(positivebings2e12, vars = "Episode")
countPBs2e13 <- count(positivebings2e13, vars = "Episode")
countPBs2e14 <- count(positivebings2e14, vars = "Episode")
countPBs2e15 <- count(positivebings2e15, vars = "Episode")
countPBs2e16 <- count(positivebings2e16, vars = "Episode")
countPBs2e17 <- count(positivebings2e17, vars = "Episode")
countPBs2e18 <- count(positivebings2e18, vars = "Episode")
countPBs2e19 <- count(positivebings2e19, vars = "Episode")
countPBs2e20 <- count(positivebings2e20, vars = "Episode")
countPBs2e21 <- count(positivebings2e21, vars = "Episode")
countPBs2e22 <- count(positivebings2e22, vars = "Episode")
## afinn Filter Negative
negativeafinns2e1 <-  afinns2e1 %>% filter(value  <= 0)
negativeafinns2e2 <-  afinns2e2 %>% filter(value  <= 0)
negativeafinns2e3 <-  afinns2e3 %>% filter(value  <= 0)
negativeafinns2e4 <-  afinns2e4 %>% filter(value  <= 0)
negativeafinns2e5 <-  afinns2e5 %>% filter(value  <= 0)
negativeafinns2e6 <-  afinns2e6 %>% filter(value  <= 0)
negativeafinns2e7 <-  afinns2e7 %>% filter(value  <= 0)
negativeafinns2e8 <-  afinns2e8 %>% filter(value  <= 0)
negativeafinns2e9 <-  afinns2e9 %>% filter(value  <= 0)
negativeafinns2e10 <- afinns2e10 %>% filter(value <= 0)
negativeafinns2e11 <- afinns2e11 %>% filter(value <= 0)
negativeafinns2e12 <- afinns2e12 %>% filter(value <= 0)
negativeafinns2e13 <- afinns2e13 %>% filter(value <= 0)
negativeafinns2e14 <- afinns2e14 %>% filter(value <= 0)
negativeafinns2e15 <- afinns2e15 %>% filter(value <= 0)
negativeafinns2e16 <- afinns2e16 %>% filter(value <= 0)
negativeafinns2e17 <- afinns2e17 %>% filter(value <= 0)
negativeafinns2e18 <- afinns2e18 %>% filter(value <= 0)
negativeafinns2e19 <- afinns2e19 %>% filter(value <= 0)
negativeafinns2e20 <- afinns2e20 %>% filter(value <= 0)
negativeafinns2e21 <- afinns2e21 %>% filter(value <= 0)
negativeafinns2e22 <- afinns2e22 %>% filter(value <= 0)
## bing Filter Negative
negativebings2e1 <-  bings2e1 %>% filter(sentiment == 'negative')
negativebings2e2 <-  bings2e2 %>% filter(sentiment == 'negative')
negativebings2e3 <-  bings2e3 %>% filter(sentiment == 'negative')
negativebings2e4 <-  bings2e4 %>% filter(sentiment == 'negative')
negativebings2e5 <-  bings2e5 %>% filter(sentiment == 'negative')
negativebings2e6 <-  bings2e6 %>% filter(sentiment == 'negative')
negativebings2e7 <-  bings2e7 %>% filter(sentiment == 'negative')
negativebings2e8 <-  bings2e8 %>% filter(sentiment == 'negative')
negativebings2e9 <-  bings2e9 %>% filter(sentiment == 'negative')
negativebings2e10 <- bings2e10 %>% filter(sentiment == 'negative')
negativebings2e11 <- bings2e11 %>% filter(sentiment == 'negative')
negativebings2e12 <- bings2e12 %>% filter(sentiment == 'negative')
negativebings2e13 <- bings2e13 %>% filter(sentiment == 'negative')
negativebings2e14 <- bings2e14 %>% filter(sentiment == 'negative')
negativebings2e15 <- bings2e15 %>% filter(sentiment == 'negative')
negativebings2e16 <- bings2e16 %>% filter(sentiment == 'negative')
negativebings2e17 <- bings2e17 %>% filter(sentiment == 'negative')
negativebings2e18 <- bings2e18 %>% filter(sentiment == 'negative')
negativebings2e19 <- bings2e19 %>% filter(sentiment == 'negative')
negativebings2e20 <- bings2e20 %>% filter(sentiment == 'negative')
negativebings2e21 <- bings2e21 %>% filter(sentiment == 'negative')
negativebings2e22 <- bings2e22 %>% filter(sentiment == 'negative')
## afinn Count Negatives
countNAs2e1 <-  count(negativeafinns2e1, vars = "Episode")
countNAs2e2 <-  count(negativeafinns2e2, vars = "Episode")
countNAs2e3 <-  count(negativeafinns2e3, vars = "Episode")
countNAs2e4 <-  count(negativeafinns2e4, vars = "Episode")
countNAs2e5 <-  count(negativeafinns2e5, vars = "Episode")
countNAs2e6 <-  count(negativeafinns2e6, vars = "Episode")
countNAs2e7 <-  count(negativeafinns2e7, vars = "Episode")
countNAs2e8 <-  count(negativeafinns2e8, vars = "Episode")
countNAs2e9 <-  count(negativeafinns2e9, vars = "Episode")
countNAs2e10 <- count(negativeafinns2e10, vars = "Episode")
countNAs2e11 <- count(negativeafinns2e11, vars = "Episode")
countNAs2e12 <- count(negativeafinns2e12, vars = "Episode")
countNAs2e13 <- count(negativeafinns2e13, vars = "Episode")
countNAs2e14 <- count(negativeafinns2e14, vars = "Episode")
countNAs2e15 <- count(negativeafinns2e15, vars = "Episode")
countNAs2e16 <- count(negativeafinns2e16, vars = "Episode")
countNAs2e17 <- count(negativeafinns2e17, vars = "Episode")
countNAs2e18 <- count(negativeafinns2e18, vars = "Episode")
countNAs2e19 <- count(negativeafinns2e19, vars = "Episode")
countNAs2e20 <- count(negativeafinns2e20, vars = "Episode")
countNAs2e21 <- count(negativeafinns2e21, vars = "Episode")
countNAs2e22 <- count(negativeafinns2e22, vars = "Episode")
## bing Count Negatives
countNBs2e1 <-  count(negativebings2e1, vars = "Episode")
countNBs2e2 <-  count(negativebings2e2, vars = "Episode")
countNBs2e3 <-  count(negativebings2e3, vars = "Episode")
countNBs2e4 <-  count(negativebings2e4, vars = "Episode")
countNBs2e5 <-  count(negativebings2e5, vars = "Episode")
countNBs2e6 <-  count(negativebings2e6, vars = "Episode")
countNBs2e7 <-  count(negativebings2e7, vars = "Episode")
countNBs2e8 <-  count(negativebings2e8, vars = "Episode")
countNBs2e9 <-  count(negativebings2e9, vars = "Episode")
countNBs2e10 <- count(negativebings2e10, vars = "Episode")
countNBs2e11 <- count(negativebings2e11, vars = "Episode")
countNBs2e12 <- count(negativebings2e12, vars = "Episode")
countNBs2e13 <- count(negativebings2e13, vars = "Episode")
countNBs2e14 <- count(negativebings2e14, vars = "Episode")
countNBs2e15 <- count(negativebings2e15, vars = "Episode")
countNBs2e16 <- count(negativebings2e16, vars = "Episode")
countNBs2e17 <- count(negativebings2e17, vars = "Episode")
countNBs2e18 <- count(negativebings2e18, vars = "Episode")
countNBs2e19 <- count(negativebings2e19, vars = "Episode")
countNBs2e20 <- count(negativebings2e20, vars = "Episode")
countNBs2e21 <- count(negativebings2e21, vars = "Episode")
countNBs2e22 <- count(negativebings2e22, vars = "Episode")
## Top 10 Positive words
## afinn
s2e1Posafinn <- positiveafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e2Posafinn <- positiveafinns2e2 %>% count(word) %>% arrange(desc(n))
s2e3Posafinn <- positiveafinns2e3 %>% count(word) %>% arrange(desc(n))
s2e4Posafinn <- positiveafinns2e4 %>% count(word) %>% arrange(desc(n))
s2e5Posafinn <- positiveafinns2e5 %>% count(word) %>% arrange(desc(n))
s2e6Posafinn <- positiveafinns2e6 %>% count(word) %>% arrange(desc(n))
s2e7Posafinn <- positiveafinns2e7 %>% count(word) %>% arrange(desc(n))
s2e8Posafinn <- positiveafinns2e8 %>% count(word) %>% arrange(desc(n))
s2e9Posafinn <- positiveafinns2e9 %>% count(word) %>% arrange(desc(n))
s2e10Posafinn <- positiveafinns2e10 %>% count(word) %>% arrange(desc(n))
s2e11Posafinn <- positiveafinns2e11 %>% count(word) %>% arrange(desc(n))
s2e12Posafinn <- positiveafinns2e12 %>% count(word) %>% arrange(desc(n))
s2e13Posafinn <- positiveafinns2e13 %>% count(word) %>% arrange(desc(n))
s2e14Posafinn <- positiveafinns2e14 %>% count(word) %>% arrange(desc(n))
s2e15Posafinn <- positiveafinns2e15 %>% count(word) %>% arrange(desc(n))
s2e16Posafinn <- positiveafinns2e16 %>% count(word) %>% arrange(desc(n))
s2e17Posafinn <- positiveafinns2e17 %>% count(word) %>% arrange(desc(n))
s2e18Posafinn <- positiveafinns2e18 %>% count(word) %>% arrange(desc(n))
s2e19Posafinn <- positiveafinns2e19 %>% count(word) %>% arrange(desc(n))
s2e20Posafinn <- positiveafinns2e20 %>% count(word) %>% arrange(desc(n))
s2e21Posafinn <- positiveafinns2e21 %>% count(word) %>% arrange(desc(n))
s2e22Posafinn <- positiveafinns2e22 %>% count(word) %>% arrange(desc(n))
# Negatives
s2e1Negafinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e2Negafinn <- negativeafinns2e2 %>% count(word) %>% arrange(desc(n))
s2e3Negafinn <- negativeafinns2e3 %>% count(word) %>% arrange(desc(n))
s2e4Negafinn <- negativeafinns2e4 %>% count(word) %>% arrange(desc(n))
s2e5Negafinn <- negativeafinns2e5 %>% count(word) %>% arrange(desc(n))
s2e6Negafinn <- negativeafinns2e6 %>% count(word) %>% arrange(desc(n))
s2e7Negafinn <- negativeafinns2e7 %>% count(word) %>% arrange(desc(n))
s2e8Negafinn <- negativeafinns2e8 %>% count(word) %>% arrange(desc(n))
s2e9Negafinn <- negativeafinns2e9 %>% count(word) %>% arrange(desc(n))
s2e10Negafinn <- negativeafinns2e10 %>% count(word) %>% arrange(desc(n))
s2e11Negafinn <- negativeafinns2e11 %>% count(word) %>% arrange(desc(n))
s2e12Negafinn <- negativeafinns2e12 %>% count(word) %>% arrange(desc(n))
s2e13Negafinn <- negativeafinns2e13 %>% count(word) %>% arrange(desc(n))
s2e14Negafinn <- negativeafinns2e14 %>% count(word) %>% arrange(desc(n))
s2e15Negafinn <- negativeafinns2e15 %>% count(word) %>% arrange(desc(n))
s2e16Negafinn <- negativeafinns2e16 %>% count(word) %>% arrange(desc(n))
s2e17Negafinn <- negativeafinns2e17 %>% count(word) %>% arrange(desc(n))
s2e18Negafinn <- negativeafinns2e18 %>% count(word) %>% arrange(desc(n))
s2e19Negafinn <- negativeafinns2e19 %>% count(word) %>% arrange(desc(n))
s2e20Negafinn <- negativeafinns2e20 %>% count(word) %>% arrange(desc(n))
s2e21Negafinn <- negativeafinns2e21 %>% count(word) %>% arrange(desc(n))
s2e22Negafinn <- negativeafinns2e22 %>% count(word) %>% arrange(desc(n))

## Top Ten bing
# Positive
s2e1Posbing <- positivebings2e1 %>% count(word) %>% arrange(desc(n))
s2e2Posbing <- positivebings2e2 %>% count(word) %>% arrange(desc(n))
s2e3Posbing <- positivebings2e3 %>% count(word) %>% arrange(desc(n))
s2e4Posbing <- positivebings2e4 %>% count(word) %>% arrange(desc(n))
s2e5Posbing <- positivebings2e5 %>% count(word) %>% arrange(desc(n))
s2e6Posbing <- positivebings2e6 %>% count(word) %>% arrange(desc(n))
s2e7Posbing <- positivebings2e7 %>% count(word) %>% arrange(desc(n))
s2e8Posbing <- positivebings2e8 %>% count(word) %>% arrange(desc(n))
s2e9Posbing <- positivebings2e9 %>% count(word) %>% arrange(desc(n))
s2e10Posbing <- positivebings2e10 %>% count(word) %>% arrange(desc(n))
s2e11Posbing <- positivebings2e11 %>% count(word) %>% arrange(desc(n))
s2e12Posbing <- positivebings2e12 %>% count(word) %>% arrange(desc(n))
s2e13Posbing <- positivebings2e13 %>% count(word) %>% arrange(desc(n))
s2e14Posbing <- positivebings2e14 %>% count(word) %>% arrange(desc(n))
s2e15Posbing <- positivebings2e15 %>% count(word) %>% arrange(desc(n))
s2e16Posbing <- positivebings2e16 %>% count(word) %>% arrange(desc(n))
s2e17Posbing <- positivebings2e17 %>% count(word) %>% arrange(desc(n))
s2e18Posbing <- positivebings2e18 %>% count(word) %>% arrange(desc(n))
s2e19Posbing <- positivebings2e19 %>% count(word) %>% arrange(desc(n))
s2e20Posbing <- positivebings2e20 %>% count(word) %>% arrange(desc(n))
s2e21Posbing <- positivebings2e21 %>% count(word) %>% arrange(desc(n))
s2e22Posbing <- positivebings2e22 %>% count(word) %>% arrange(desc(n))
# Negatives
s2e1Negbing <- negativebings2e1 %>% count(word) %>% arrange(desc(n))
s2e2Negbing <- negativebings2e2 %>% count(word) %>% arrange(desc(n))
s2e3Negbing <- negativebings2e3 %>% count(word) %>% arrange(desc(n))
s2e4Negbing <- negativebings2e4 %>% count(word) %>% arrange(desc(n))
s2e5Negbing <- negativebings2e5 %>% count(word) %>% arrange(desc(n))
s2e6Negbing <- negativebings2e6 %>% count(word) %>% arrange(desc(n))
s2e7Negbing <- negativebings2e7 %>% count(word) %>% arrange(desc(n))
s2e8Negbing <- negativebings2e8 %>% count(word) %>% arrange(desc(n))
s2e9Negbing <- negativebings2e9 %>% count(word) %>% arrange(desc(n))
s2e10Negbing <- negativebings2e10 %>% count(word) %>% arrange(desc(n))
s2e11Negbing <- negativebings2e11 %>% count(word) %>% arrange(desc(n))
s2e12Negbing <- negativebings2e12 %>% count(word) %>% arrange(desc(n))
s2e13Negbing <- negativebings2e13 %>% count(word) %>% arrange(desc(n))
s2e14Negbing <- negativebings2e14 %>% count(word) %>% arrange(desc(n))
s2e15Negbing <- negativebings2e15 %>% count(word) %>% arrange(desc(n))
s2e16Negbing <- negativebings2e16 %>% count(word) %>% arrange(desc(n))
s2e17Negbing <- negativebings2e17 %>% count(word) %>% arrange(desc(n))
s2e18Negbing <- negativebings2e18 %>% count(word) %>% arrange(desc(n))
s2e19Negbing <- negativebings2e19 %>% count(word) %>% arrange(desc(n))
s2e20Negbing <- negativebings2e20 %>% count(word) %>% arrange(desc(n))
s2e21Negbing <- negativebings2e21 %>% count(word) %>% arrange(desc(n))
s2e22Negbing <- negativebings2e22 %>% count(word) %>% arrange(desc(n))

## Save them out
## Save Season 2 afinns
# Positive
write.csv(s2e1Posafinn, file = "top-ten/season2/Posafinns2e1.csv")
write.csv(s2e2Posafinn, file = "top-ten/season2/Posafinns2e2.csv")
write.csv(s2e3Posafinn, file = "top-ten/season2/Posafinns2e3.csv")
write.csv(s2e4Posafinn, file = "top-ten/season2/Posafinns2e4.csv")
write.csv(s2e5Posafinn, file = "top-ten/season2/Posafinns2e5.csv")
write.csv(s2e6Posafinn, file = "top-ten/season2/Posafinns2e6.csv")
write.csv(s2e7Posafinn, file = "top-ten/season2/Posafinns2e7.csv")
write.csv(s2e8Posafinn, file = "top-ten/season2/Posafinns2e8.csv")
write.csv(s2e9Posafinn, file = "top-ten/season2/Posafinns2e9.csv")
write.csv(s2e10Posafinn, file = "top-ten/season2/Posafinns2e10.csv")
write.csv(s2e11Posafinn, file = "top-ten/season2/Posafinns2e11.csv")
write.csv(s2e12Posafinn, file = "top-ten/season2/Posafinns2e12.csv")
write.csv(s2e13Posafinn, file = "top-ten/season2/Posafinns2e13.csv")
write.csv(s2e14Posafinn, file = "top-ten/season2/Posafinns2e14.csv")
write.csv(s2e15Posafinn, file = "top-ten/season2/Posafinns2e15.csv")
write.csv(s2e16Posafinn, file = "top-ten/season2/Posafinns2e16.csv")
write.csv(s2e17Posafinn, file = "top-ten/season2/Posafinns2e17.csv")
write.csv(s2e18Posafinn, file = "top-ten/season2/Posafinns2e18.csv")
write.csv(s2e19Posafinn, file = "top-ten/season2/Posafinns2e19.csv")
write.csv(s2e20Posafinn, file = "top-ten/season2/Posafinns2e20.csv")
write.csv(s2e21Posafinn, file = "top-ten/season2/Posafinns2e21.csv")
write.csv(s2e22Posafinn, file = "top-ten/season2/Posafinns2e22.csv")
# Negatives
write.csv(s2e1Negafinn, file = "top-ten/season2/Negafinns2e1.csv")
write.csv(s2e2Negafinn, file = "top-ten/season2/Negafinns2e2.csv")
write.csv(s2e3Negafinn, file = "top-ten/season2/Negafinns2e3.csv")
write.csv(s2e4Negafinn, file = "top-ten/season2/Negafinns2e4.csv")
write.csv(s2e5Negafinn, file = "top-ten/season2/Negafinns2e5.csv")
write.csv(s2e6Negafinn, file = "top-ten/season2/Negafinns2e6.csv")
write.csv(s2e7Negafinn, file = "top-ten/season2/Negafinns2e7.csv")
write.csv(s2e8Negafinn, file = "top-ten/season2/Negafinns2e8.csv")
write.csv(s2e9Negafinn, file = "top-ten/season2/Negafinns2e9.csv")
write.csv(s2e10Negafinn, file = "top-ten/season2/Negafinns2e10.csv")
write.csv(s2e11Negafinn, file = "top-ten/season2/Negafinns2e11.csv")
write.csv(s2e12Negafinn, file = "top-ten/season2/Negafinns2e12.csv")
write.csv(s2e13Negafinn, file = "top-ten/season2/Negafinns2e13.csv")
write.csv(s2e14Negafinn, file = "top-ten/season2/Negafinns2e14.csv")
write.csv(s2e15Negafinn, file = "top-ten/season2/Negafinns2e15.csv")
write.csv(s2e16Negafinn, file = "top-ten/season2/Negafinns2e16.csv")
write.csv(s2e17Negafinn, file = "top-ten/season2/Negafinns2e17.csv")
write.csv(s2e18Negafinn, file = "top-ten/season2/Negafinns2e18.csv")
write.csv(s2e19Negafinn, file = "top-ten/season2/Negafinns2e19.csv")
write.csv(s2e20Negafinn, file = "top-ten/season2/Negafinns2e20.csv")
write.csv(s2e21Negafinn, file = "top-ten/season2/Negafinns2e21.csv")
write.csv(s2e22Negafinn, file = "top-ten/season2/Negafinns2e22.csv")
## bing
write.csv(s2e1Posbing, file = "top-ten/season2/Posbings2e1.csv")
write.csv(s2e2Posbing, file = "top-ten/season2/Posbings2e2.csv")
write.csv(s2e3Posbing, file = "top-ten/season2/Posbings2e3.csv")
write.csv(s2e4Posbing, file = "top-ten/season2/Posbings2e4.csv")
write.csv(s2e5Posbing, file = "top-ten/season2/Posbings2e5.csv")
write.csv(s2e6Posbing, file = "top-ten/season2/Posbings2e6.csv")
write.csv(s2e7Posbing, file = "top-ten/season2/Posbings2e7.csv")
write.csv(s2e8Posbing, file = "top-ten/season2/Posbings2e8.csv")
write.csv(s2e9Posbing, file = "top-ten/season2/Posbings2e9.csv")
write.csv(s2e10Posbing, file = "top-ten/season2/Posbings2e10.csv")
write.csv(s2e11Posbing, file = "top-ten/season2/Posbings2e11.csv")
write.csv(s2e12Posbing, file = "top-ten/season2/Posbings2e12.csv")
write.csv(s2e13Posbing, file = "top-ten/season2/Posbings2e13.csv")
write.csv(s2e14Posbing, file = "top-ten/season2/Posbings2e14.csv")
write.csv(s2e15Posbing, file = "top-ten/season2/Posbings2e15.csv")
write.csv(s2e16Posbing, file = "top-ten/season2/Posbings2e16.csv")
write.csv(s2e17Posbing, file = "top-ten/season2/Posbings2e17.csv")
write.csv(s2e18Posbing, file = "top-ten/season2/Posbings2e18.csv")
write.csv(s2e19Posbing, file = "top-ten/season2/Posbings2e19.csv")
write.csv(s2e20Posbing, file = "top-ten/season2/Posbings2e20.csv")
write.csv(s2e21Posbing, file = "top-ten/season2/Posbings2e21.csv")
write.csv(s2e22Posbing, file = "top-ten/season2/Posbings2e22.csv")
# Negatives
write.csv(s2e1Negbing, file = "top-ten/season2/Negbings2e1.csv")
write.csv(s2e2Negbing, file = "top-ten/season2/Negbings2e2.csv")
write.csv(s2e3Negbing, file = "top-ten/season2/Negbings2e3.csv")
write.csv(s2e4Negbing, file = "top-ten/season2/Negbings2e4.csv")
write.csv(s2e5Negbing, file = "top-ten/season2/Negbings2e5.csv")
write.csv(s2e6Negbing, file = "top-ten/season2/Negbings2e6.csv")
write.csv(s2e7Negbing, file = "top-ten/season2/Negbings2e7.csv")
write.csv(s2e8Negbing, file = "top-ten/season2/Negbings2e8.csv")
write.csv(s2e9Negbing, file = "top-ten/season2/Negbings2e9.csv")
write.csv(s2e10Negbing, file = "top-ten/season2/Negbings2e10.csv")
write.csv(s2e11Negbing, file = "top-ten/season2/Negbings2e11.csv")
write.csv(s2e12Negbing, file = "top-ten/season2/Negbings2e12.csv")
write.csv(s2e13Negbing, file = "top-ten/season2/Negbings2e13.csv")
write.csv(s2e14Negbing, file = "top-ten/season2/Negbings2e14.csv")
write.csv(s2e15Negbing, file = "top-ten/season2/Negbings2e15.csv")
write.csv(s2e16Negbing, file = "top-ten/season2/Negbings2e16.csv")
write.csv(s2e17Negbing, file = "top-ten/season2/Negbings2e17.csv")
write.csv(s2e18Negbing, file = "top-ten/season2/Negbings2e18.csv")
write.csv(s2e19Negbing, file = "top-ten/season2/Negbings2e19.csv")
write.csv(s2e20Negbing, file = "top-ten/season2/Negbings2e20.csv")
write.csv(s2e21Negbing, file = "top-ten/season2/Negbings2e21.csv")
write.csv(s2e22Negbing, file = "top-ten/season2/Negbings2e22.csv")

## Bind Season 2
seasonTwo <- bind_rows(tokenS2E1,tokenS2E2,tokenS2E3,tokenS2E4,tokenS2E5,tokenS2E6,tokenS2E7,tokenS2E8,tokenS2E9,tokenS2E10,tokenS2E11,tokenS2E12,tokenS2E13,tokenS2E14,tokenS2E15,tokenS2E16,tokenS2E17,tokenS2E18,tokenS2E19,tokenS2E20,tokenS2E21,tokenS2E22)
## Positive Words, with value and count
affinPosS2 <- seasonTwo %>% inner_join(get_sentiments('afinn')) %>%
  count(word, value, sort = TRUE) %>% ungroup() %>% filter(value >= 1)
## Negative Words, with value and count
affinNegS2 <- seasonTwo %>% inner_join(get_sentiments('afinn')) %>%
  count(word, value, sort = TRUE) %>% ungroup() %>% filter(value <= -1)
## Count the bing words.
countBingS2 <- seasonTwo %>% inner_join(get_sentiments('bing')) %>%
  count(word, sentiment, sort = TRUE) %>% ungroup()
## Save them both out
write.csv(affinPosS2, file = "top-ten/#APS2.csv")
write.csv(affinNegS2, file = "top-ten/#ANS2.csv")
write.csv(countBingS2, file = "top-ten/#BS2.csv")