## Season 2 - Sentiment Analysis - Twin Peaks
## Mark Baber
## Load Libraries
library(dplyr)
library(tidytext)
library(tidyverse)
library(tidyr)
library(stringr)
library(readr)

## Season 3
## Import Datasets
s3e1 <- read.csv("s3e1-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e2 <- read.csv("s3e2-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e3 <- read.csv("s3e3-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e4 <- read.csv("s3e4-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e5 <- read.csv("s3e5-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e6 <- read.csv("s3e6-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e7 <- read.csv("s3e7-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e8 <- read.csv("s3e8-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e9 <- read.csv("s3e9-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e10 <- read.csv("s3e10-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e11 <- read.csv("s3e11-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e12 <- read.csv("s3e12-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e13 <- read.csv("s3e13-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e14 <- read.csv("s3e14-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e15 <- read.csv("s3e15-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e16 <- read.csv("s3e16-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e17 <- read.csv("s3e17-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e18 <- read.csv("s3e18-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
## create a tibble with the Episode ([,1]) & Words ([,2])
tibs3e1 <- tibble(Episode = s3e1[,1], Words = s3e1[,2])
tibs3e2 <- tibble(Episode = s3e2[,1], Words = s3e2[,2])
tibs3e3 <- tibble(Episode = s3e3[,1], Words = s3e3[,2])
tibs3e4 <- tibble(Episode = s3e4[,1], Words = s3e4[,2])
tibs3e5 <- tibble(Episode = s3e5[,1], Words = s3e5[,2])
tibs3e6 <- tibble(Episode = s3e6[,1], Words = s3e6[,2])
tibs3e7 <- tibble(Episode = s3e7[,1], Words = s3e7[,2])
tibs3e8 <- tibble(Episode = s3e8[,1], Words = s3e8[,2])
tibs3e9 <- tibble(Episode = s3e9[,1], Words = s3e9[,2])
tibs3e10 <- tibble(Episode = s3e10[,1], Words = s3e10[,2])
tibs3e11 <- tibble(Episode = s3e11[,1], Words = s3e11[,2])
tibs3e12 <- tibble(Episode = s3e12[,1], Words = s3e12[,2])
tibs3e13 <- tibble(Episode = s3e13[,1], Words = s3e13[,2])
tibs3e14 <- tibble(Episode = s3e14[,1], Words = s3e14[,2])
tibs3e15 <- tibble(Episode = s3e15[,1], Words = s3e15[,2])
tibs3e16 <- tibble(Episode = s3e16[,1], Words = s3e16[,2])
tibs3e17 <- tibble(Episode = s3e17[,1], Words = s3e17[,2])
tibs3e18 <- tibble(Episode = s3e18[,1], Words = s3e18[,2])
# Token the words
TokenS3E1 <- tibs3e1 %>% unnest_tokens(word, Words)
TokenS3E2 <- tibs3e2 %>% unnest_tokens(word, Words)
TokenS3E3 <- tibs3e3 %>% unnest_tokens(word, Words)
TokenS3E4 <- tibs3e4 %>% unnest_tokens(word, Words)
TokenS3E5 <- tibs3e5 %>% unnest_tokens(word, Words)
TokenS3E6 <- tibs3e6 %>% unnest_tokens(word, Words)
TokenS3E7 <- tibs3e7 %>% unnest_tokens(word, Words)
TokenS3E8 <- tibs3e8 %>% unnest_tokens(word, Words)
TokenS3E9 <- tibs3e9 %>% unnest_tokens(word, Words)
TokenS3E10 <- tibs3e10 %>% unnest_tokens(word, Words)
TokenS3E11 <- tibs3e11 %>% unnest_tokens(word, Words)
TokenS3E12 <- tibs3e12 %>% unnest_tokens(word, Words)
TokenS3E13 <- tibs3e13 %>% unnest_tokens(word, Words)
TokenS3E14 <- tibs3e14 %>% unnest_tokens(word, Words)
TokenS3E15 <- tibs3e15 %>% unnest_tokens(word, Words)
TokenS3E16 <- tibs3e16 %>% unnest_tokens(word, Words)
TokenS3E17 <- tibs3e17 %>% unnest_tokens(word, Words)
TokenS3E18 <- tibs3e18 %>% unnest_tokens(word, Words)

## Affin
afinns3e1 <- tibs3e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e2 <- tibs3e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e3 <- tibs3e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e4 <- tibs3e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e5 <- tibs3e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e6 <- tibs3e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e7 <- tibs3e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e8 <- tibs3e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e9 <- tibs3e9 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e10 <- tibs3e10 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e11 <- tibs3e11 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e12 <- tibs3e12 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e13 <- tibs3e13 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e14 <- tibs3e14 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e15 <- tibs3e15 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e16 <- tibs3e16 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e17 <- tibs3e17 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e18 <- tibs3e18 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
## bing
bings3e1 <- tibs3e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e2 <- tibs3e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e3 <- tibs3e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e4 <- tibs3e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e5 <- tibs3e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e6 <- tibs3e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e7 <- tibs3e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e8 <- tibs3e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e9 <- tibs3e9 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e10 <- tibs3e10 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e11 <- tibs3e11 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e12 <- tibs3e12 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e13 <- tibs3e13 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e14 <- tibs3e14 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e15 <- tibs3e15 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e16 <- tibs3e16 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e17 <- tibs3e17 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e18 <- tibs3e18 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
## afinn Count
countafinns3e1 <- count(afinns3e1, vars = "Episode")
countafinns3e2 <- count(afinns3e2, vars = "Episode")
countafinns3e3 <- count(afinns3e3, vars = "Episode")
countafinns3e4 <- count(afinns3e4, vars = "Episode")
countafinns3e5 <- count(afinns3e5, vars = "Episode")
countafinns3e6 <- count(afinns3e6, vars = "Episode")
countafinns3e7 <- count(afinns3e7, vars = "Episode")
countafinns3e8 <- count(afinns3e8, vars = "Episode")
countafinns3e9 <- count(afinns3e9, vars = "Episode")
countafinns3e10 <- count(afinns3e10, vars = "Episode")
countafinns3e11 <- count(afinns3e11, vars = "Episode")
countafinns3e12 <- count(afinns3e12, vars = "Episode")
countafinns3e13 <- count(afinns3e13, vars = "Episode")
countafinns3e14 <- count(afinns3e14, vars = "Episode")
countafinns3e15 <- count(afinns3e15, vars = "Episode")
countafinns3e16 <- count(afinns3e16, vars = "Episode")
countafinns3e17 <- count(afinns3e17, vars = "Episode")
countafinns3e18 <- count(afinns3e18, vars = "Episode")
## bing Count
countbings3e1 <- count(bings3e1, vars = "Episode")
countbings3e2 <- count(bings3e2, vars = "Episode")
countbings3e3 <- count(bings3e3, vars = "Episode")
countbings3e4 <- count(bings3e4, vars = "Episode")
countbings3e5 <- count(bings3e5, vars = "Episode")
countbings3e6 <- count(bings3e6, vars = "Episode")
countbings3e7 <- count(bings3e7, vars = "Episode")
countbings3e8 <- count(bings3e8, vars = "Episode")
countbings3e9 <- count(bings3e9, vars = "Episode")
countbings3e10 <- count(bings3e10, vars = "Episode")
countbings3e11 <- count(bings3e11, vars = "Episode")
countbings3e12 <- count(bings3e12, vars = "Episode")
countbings3e13 <- count(bings3e13, vars = "Episode")
countbings3e14 <- count(bings3e14, vars = "Episode")
countbings3e15 <- count(bings3e15, vars = "Episode")
countbings3e16 <- count(bings3e16, vars = "Episode")
countbings3e17 <- count(bings3e17, vars = "Episode")
countbings3e18 <- count(bings3e18, vars = "Episode")
## afinn Filter Positive
positiveAfinns3e1 <- afinns3e1 %>% filter(value >= 0)
positiveAsfinn3e2 <- afinns3e2 %>% filter(value >= 0)
positiveAsfinn3e3 <- afinns3e3 %>% filter(value >= 0)
positiveAsfinn3e4 <- afinns3e4 %>% filter(value >= 0)
positiveAsfinn3e5 <- afinns3e5 %>% filter(value >= 0)
positiveAsfinn3e6 <- afinns3e6 %>% filter(value >= 0)
positiveAsfinn3e7 <- afinns3e7 %>% filter(value >= 0)
positiveAsfinn3e8 <- afinns3e8 %>% filter(value >= 0)
positiveAsfinn3e9 <- afinns3e9 %>% filter(value >= 0)
positiveAsfinn3e10 <- afinns3e10 %>% filter(value >= 0)
positiveAsfinn3e11 <- afinns3e11 %>% filter(value >= 0)
positiveAsfinn3e12 <- afinns3e12 %>% filter(value >= 0)
positiveAsfinn3e13 <- afinns3e13 %>% filter(value >= 0)
positiveAsfinn3e14 <- afinns3e14 %>% filter(value >= 0)
positiveAsfinn3e15 <- afinns3e15 %>% filter(value >= 0)
positiveAsfinn3e16 <- afinns3e16 %>% filter(value >= 0)
positiveAsfinn3e17 <- afinns3e17 %>% filter(value >= 0)
positiveAsfinn3e18 <- afinns3e18 %>% filter(value >= 0)
## bing Filter Positive
positiveBings3e1 <- bings3e1 %>% filter(sentiment == 'positive')
positiveBings3e2 <- bings3e2 %>% filter(sentiment == 'positive')
positiveBings3e3 <- bings3e3 %>% filter(sentiment == 'positive')
positiveBings3e4 <- bings3e4 %>% filter(sentiment == 'positive')
positiveBings3e5 <- bings3e5 %>% filter(sentiment == 'positive')
positiveBings3e6 <- bings3e6 %>% filter(sentiment == 'positive')
positiveBings3e7 <- bings3e7 %>% filter(sentiment == 'positive')
positiveBings3e8 <- bings3e8 %>% filter(sentiment == 'positive')
positiveBings3e9 <- bings3e9 %>% filter(sentiment == 'positive')
positiveBings3e10 <- bings3e10 %>% filter(sentiment == 'positive')
positiveBings3e11 <- bings3e11 %>% filter(sentiment == 'positive')
positiveBings3e12 <- bings3e12 %>% filter(sentiment == 'positive')
positiveBings3e13 <- bings3e13 %>% filter(sentiment == 'positive')
positiveBings3e14 <- bings3e14 %>% filter(sentiment == 'positive')
positiveBings3e15 <- bings3e15 %>% filter(sentiment == 'positive')
positiveBings3e16 <- bings3e16 %>% filter(sentiment == 'positive')
positiveBings3e17 <- bings3e17 %>% filter(sentiment == 'positive')
positiveBings3e18 <- bings3e18 %>% filter(sentiment == 'positive')
## afinn Count Positives
countPAs3e1 <- count(positiveAs3e1, vars = "Episode")
countPAs3e2 <- count(positiveAs3e2, vars = "Episode")
countPAs3e3 <- count(positiveAs3e3, vars = "Episode")
countPAs3e4 <- count(positiveAs3e4, vars = "Episode")
countPAs3e5 <- count(positiveAs3e5, vars = "Episode")
countPAs3e6 <- count(positiveAs3e6, vars = "Episode")
countPAs3e7 <- count(positiveAs3e7, vars = "Episode")
countPAs3e8 <- count(positiveAs3e8, vars = "Episode")
countPAs3e9 <- count(positiveAs3e9, vars = "Episode")
countPAs3e10 <- count(positiveAs3e10, vars = "Episode")
countPAs3e11 <- count(positiveAs3e11, vars = "Episode")
countPAs3e12 <- count(positiveAs3e12, vars = "Episode")
countPAs3e13 <- count(positiveAs3e13, vars = "Episode")
countPAs3e14 <- count(positiveAs3e14, vars = "Episode")
countPAs3e15 <- count(positiveAs3e15, vars = "Episode")
countPAs3e16 <- count(positiveAs3e16, vars = "Episode")
countPAs3e17 <- count(positiveAs3e17, vars = "Episode")
countPAs3e18 <- count(positiveAs3e18, vars = "Episode")
## bing Count Positives
countPBs3e1 <- count(positiveBs3e1, vars = "Episode")
countPBs3e2 <- count(positiveBs3e2, vars = "Episode")
countPBs3e3 <- count(positiveBs3e3, vars = "Episode")
countPBs3e4 <- count(positiveBs3e4, vars = "Episode")
countPBs3e5 <- count(positiveBs3e5, vars = "Episode")
countPBs3e6 <- count(positiveBs3e6, vars = "Episode")
countPBs3e7 <- count(positiveBs3e7, vars = "Episode")
countPBs3e8 <- count(positiveBs3e8, vars = "Episode")
countPBs3e9 <- count(positiveBs3e9, vars = "Episode")
countPBs3e10 <- count(positiveBs3e10, vars = "Episode")
countPBs3e11 <- count(positiveBs3e11, vars = "Episode")
countPBs3e12 <- count(positiveBs3e12, vars = "Episode")
countPBs3e13 <- count(positiveBs3e13, vars = "Episode")
countPBs3e14 <- count(positiveBs3e14, vars = "Episode")
countPBs3e15 <- count(positiveBs3e15, vars = "Episode")
countPBs3e16 <- count(positiveBs3e16, vars = "Episode")
countPBs3e17 <- count(positiveBs3e17, vars = "Episode")
countPBs3e18 <- count(positiveBs3e18, vars = "Episode")
## bing Filter Negative
negativeBs3e1 <- bings3e1 %>% filter(sentiment == 'negative')
negativeBs3e2 <- bings3e2 %>% filter(sentiment == 'negative')
negativeBs3e3 <- bings3e3 %>% filter(sentiment == 'negative')
negativeBs3e4 <- bings3e4 %>% filter(sentiment == 'negative')
negativeBs3e5 <- bings3e5 %>% filter(sentiment == 'negative')
negativeBs3e6 <- bings3e6 %>% filter(sentiment == 'negative')
negativeBs3e7 <- bings3e7 %>% filter(sentiment == 'negative')
negativeBs3e8 <- bings3e8 %>% filter(sentiment == 'negative')
negativeBs3e9 <- bings3e9 %>% filter(sentiment == 'negative')
negativeBs3e10 <- bings3e10 %>% filter(sentiment == 'negative')
negativeBs3e11 <- bings3e11 %>% filter(sentiment == 'negative')
negativeBs3e12 <- bings3e12 %>% filter(sentiment == 'negative')
negativeBs3e13 <- bings3e13 %>% filter(sentiment == 'negative')
negativeBs3e14 <- bings3e14 %>% filter(sentiment == 'negative')
negativeBs3e15 <- bings3e15 %>% filter(sentiment == 'negative')
negativeBs3e16 <- bings3e16 %>% filter(sentiment == 'negative')
negativeBs3e17 <- bings3e17 %>% filter(sentiment == 'negative')
negativeBs3e18 <- bings3e18 %>% filter(sentiment == 'negative')
## afinn Count Negatives
countNAs3e1 <- count(negativeAs3e1, vars = "Episode")
countNAs3e2 <- count(negativeAs3e2, vars = "Episode")
countNAs3e3 <- count(negativeAs3e3, vars = "Episode")
countNAs3e4 <- count(negativeAs3e4, vars = "Episode")
countNAs3e5 <- count(negativeAs3e5, vars = "Episode")
countNAs3e6 <- count(negativeAs3e6, vars = "Episode")
countNAs3e7 <- count(negativeAs3e7, vars = "Episode")
countNAs3e8 <- count(negativeAs3e8, vars = "Episode")
countNAs3e9 <- count(negativeAs3e9, vars = "Episode")
countNAs3e10 <- count(negativeAs3e10, vars = "Episode")
countNAs3e11 <- count(negativeAs3e11, vars = "Episode")
countNAs3e12 <- count(negativeAs3e12, vars = "Episode")
countNAs3e13 <- count(negativeAs3e13, vars = "Episode")
countNAs3e14 <- count(negativeAs3e14, vars = "Episode")
countNAs3e15 <- count(negativeAs3e15, vars = "Episode")
countNAs3e16 <- count(negativeAs3e16, vars = "Episode")
countNAs3e17 <- count(negativeAs3e17, vars = "Episode")
countNAs3e18 <- count(negativeAs3e18, vars = "Episode")
## bing Count Negatives
countNBs3e1 <- count(negativeBs3e1, vars = "Episode")
countNBs3e2 <- count(negativeBs3e2, vars = "Episode")
countNBs3e3 <- count(negativeBs3e3, vars = "Episode")
countNBs3e4 <- count(negativeBs3e4, vars = "Episode")
countNBs3e5 <- count(negativeBs3e5, vars = "Episode")
countNBs3e6 <- count(negativeBs3e6, vars = "Episode")
countNBs3e7 <- count(negativeBs3e7, vars = "Episode")
countNBs3e8 <- count(negativeBs3e8, vars = "Episode")
countNBs3e9 <- count(negativeBs3e9, vars = "Episode")
countNBs3e10 <- count(negativeBs3e10, vars = "Episode")
countNBs3e11 <- count(negativeBs3e11, vars = "Episode")
countNBs3e12 <- count(negativeBs3e12, vars = "Episode")
countNBs3e13 <- count(negativeBs3e13, vars = "Episode")
countNBs3e14 <- count(negativeBs3e14, vars = "Episode")
countNBs3e15 <- count(negativeBs3e15, vars = "Episode")
countNBs3e16 <- count(negativeBs3e16, vars = "Episode")
countNBs3e17 <- count(negativeBs3e17, vars = "Episode")
countNBs3e18 <- count(negativeBs3e18, vars = "Episode")

## Top 10 Positive words
## afinn
s3e1Posafinn  <- positiveAfinns3e1  %>% count(word) %>% arrange(desc(n))
s3e2Posafinn  <- positiveAfinns3e2  %>% count(word) %>% arrange(desc(n))
s3e3Posafinn  <- positiveAfinns3e3  %>% count(word) %>% arrange(desc(n))
s3e4Posafinn  <- positiveAfinns3e4  %>% count(word) %>% arrange(desc(n))
s3e5Posafinn  <- positiveAfinns3e5  %>% count(word) %>% arrange(desc(n))
s3e6Posafinn  <- positiveAfinns3e6  %>% count(word) %>% arrange(desc(n))
s3e7Posafinn  <- positiveAfinns3e7  %>% count(word) %>% arrange(desc(n))
s3e8Posafinn  <- positiveAfinns3e8  %>% count(word) %>% arrange(desc(n))
s3e9Posafinn  <- positiveAfinns3e9  %>% count(word) %>% arrange(desc(n))
s3e10Posafinn <- positiveAfinns3e10 %>% count(word) %>% arrange(desc(n))
s3e11Posafinn <- positiveAfinns3e11 %>% count(word) %>% arrange(desc(n))
s3e12Posafinn <- positiveAfinns3e12 %>% count(word) %>% arrange(desc(n))
s3e13Posafinn <- positiveAfinns3e13 %>% count(word) %>% arrange(desc(n))
s3e14Posafinn <- positiveAfinns3e14 %>% count(word) %>% arrange(desc(n))
s3e15Posafinn <- positiveAfinns3e15 %>% count(word) %>% arrange(desc(n))
s3e16Posafinn <- positiveAfinns3e16 %>% count(word) %>% arrange(desc(n))
s3e17Posafinn <- positiveAfinns3e17 %>% count(word) %>% arrange(desc(n))
s3e18Posafinn <- positiveAfinns3e18 %>% count(word) %>% arrange(desc(n))

# Negatives
s2e1Negafinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e2Negafinn <- negativeafinns2e2 %>% count(word) %>% arrange(desc(n))
s2e3Negafinn <- negativeafinns2e3 %>% count(word) %>% arrange(desc(n))
s2e4Negafinn <- negativeafinns2e4 %>% count(word) %>% arrange(desc(n))
s2e5Negafinn <- negativeafinns2e5 %>% count(word) %>% arrange(desc(n))
s2e6Negafinn <- negativeafinns2e6 %>% count(word) %>% arrange(desc(n))
s2e7Negafinn <- negativeafinns2e7 %>% count(word) %>% arrange(desc(n))
s2e8Negafinn <- negativeafinns2e8 %>% count(word) %>% arrange(desc(n))
s2e9Negafinn <- negativeafinns2e9 %>% count(word) %>% arrange(desc(n))
s2e10Negafinn <- negativeafinns2e10 %>% count(word) %>% arrange(desc(n))
s2e11Negafinn <- negativeafinns2e11 %>% count(word) %>% arrange(desc(n))
s2e12Negafinn <- negativeafinns2e12 %>% count(word) %>% arrange(desc(n))
s2e13Negafinn <- negativeafinns2e13 %>% count(word) %>% arrange(desc(n))
s2e14Negafinn <- negativeafinns2e14 %>% count(word) %>% arrange(desc(n))
s2e15Negafinn <- negativeafinns2e15 %>% count(word) %>% arrange(desc(n))
s2e16Negafinn <- negativeafinns2e16 %>% count(word) %>% arrange(desc(n))
s2e17Negafinn <- negativeafinns2e17 %>% count(word) %>% arrange(desc(n))
s2e18Negafinn <- negativeafinns2e18 %>% count(word) %>% arrange(desc(n))
s2e19Negafinn <- negativeafinns2e19 %>% count(word) %>% arrange(desc(n))
s2e20Negafinn <- negativeafinns2e20 %>% count(word) %>% arrange(desc(n))
s2e21Negafinn <- negativeafinns2e21 %>% count(word) %>% arrange(desc(n))
s2e22Negafinn <- negativeafinns2e22 %>% count(word) %>% arrange(desc(n))

## Top Ten bing
# Positive
s2e1Posbing <- positivebings2e1 %>% count(word) %>% arrange(desc(n))
s2e2Posbing <- positivebings2e2 %>% count(word) %>% arrange(desc(n))
s2e3Posbing <- positivebings2e3 %>% count(word) %>% arrange(desc(n))
s2e4Posbing <- positivebings2e4 %>% count(word) %>% arrange(desc(n))
s2e5Posbing <- positivebings2e5 %>% count(word) %>% arrange(desc(n))
s2e6Posbing <- positivebings2e6 %>% count(word) %>% arrange(desc(n))
s2e7Posbing <- positivebings2e7 %>% count(word) %>% arrange(desc(n))
s2e8Posbing <- positivebings2e8 %>% count(word) %>% arrange(desc(n))
s2e9Posbing <- positivebings2e9 %>% count(word) %>% arrange(desc(n))
s2e10Posbing <- positivebings2e10 %>% count(word) %>% arrange(desc(n))
s2e11Posbing <- positivebings2e11 %>% count(word) %>% arrange(desc(n))
s2e12Posbing <- positivebings2e12 %>% count(word) %>% arrange(desc(n))
s2e13Posbing <- positivebings2e13 %>% count(word) %>% arrange(desc(n))
s2e14Posbing <- positivebings2e14 %>% count(word) %>% arrange(desc(n))
s2e15Posbing <- positivebings2e15 %>% count(word) %>% arrange(desc(n))
s2e16Posbing <- positivebings2e16 %>% count(word) %>% arrange(desc(n))
s2e17Posbing <- positivebings2e17 %>% count(word) %>% arrange(desc(n))
s2e18Posbing <- positivebings2e18 %>% count(word) %>% arrange(desc(n))
s2e19Posbing <- positivebings2e19 %>% count(word) %>% arrange(desc(n))
s2e20Posbing <- positivebings2e20 %>% count(word) %>% arrange(desc(n))
s2e21Posbing <- positivebings2e21 %>% count(word) %>% arrange(desc(n))
s2e22Posbing <- positivebings2e22 %>% count(word) %>% arrange(desc(n))
# Negatives
s2e1Negbing <- negativebings2e1 %>% count(word) %>% arrange(desc(n))
s2e2Negbing <- negativebings2e2 %>% count(word) %>% arrange(desc(n))
s2e3Negbing <- negativebings2e3 %>% count(word) %>% arrange(desc(n))
s2e4Negbing <- negativebings2e4 %>% count(word) %>% arrange(desc(n))
s2e5Negbing <- negativebings2e5 %>% count(word) %>% arrange(desc(n))
s2e6Negbing <- negativebings2e6 %>% count(word) %>% arrange(desc(n))
s2e7Negbing <- negativebings2e7 %>% count(word) %>% arrange(desc(n))
s2e8Negbing <- negativebings2e8 %>% count(word) %>% arrange(desc(n))
s2e9Negbing <- negativebings2e9 %>% count(word) %>% arrange(desc(n))
s2e10Negbing <- negativebings2e10 %>% count(word) %>% arrange(desc(n))
s2e11Negbing <- negativebings2e11 %>% count(word) %>% arrange(desc(n))
s2e12Negbing <- negativebings2e12 %>% count(word) %>% arrange(desc(n))
s2e13Negbing <- negativebings2e13 %>% count(word) %>% arrange(desc(n))
s2e14Negbing <- negativebings2e14 %>% count(word) %>% arrange(desc(n))
s2e15Negbing <- negativebings2e15 %>% count(word) %>% arrange(desc(n))
s2e16Negbing <- negativebings2e16 %>% count(word) %>% arrange(desc(n))
s2e17Negbing <- negativebings2e17 %>% count(word) %>% arrange(desc(n))
s2e18Negbing <- negativebings2e18 %>% count(word) %>% arrange(desc(n))
s2e19Negbing <- negativebings2e19 %>% count(word) %>% arrange(desc(n))
s2e20Negbing <- negativebings2e20 %>% count(word) %>% arrange(desc(n))
s2e21Negbing <- negativebings2e21 %>% count(word) %>% arrange(desc(n))
s2e22Negbing <- negativebings2e22 %>% count(word) %>% arrange(desc(n))

## Save them out
## Save Season 2 afinns
# Positive
write.csv(s2e1Posafinn, file = "top-ten/season2/Posafinns2e1.csv")
write.csv(s2e2Posafinn, file = "top-ten/season2/Posafinns2e2.csv")
write.csv(s2e3Posafinn, file = "top-ten/season2/Posafinns2e3.csv")
write.csv(s2e4Posafinn, file = "top-ten/season2/Posafinns2e4.csv")
write.csv(s2e5Posafinn, file = "top-ten/season2/Posafinns2e5.csv")
write.csv(s2e6Posafinn, file = "top-ten/season2/Posafinns2e6.csv")
write.csv(s2e7Posafinn, file = "top-ten/season2/Posafinns2e7.csv")
write.csv(s2e8Posafinn, file = "top-ten/season2/Posafinns2e8.csv")
write.csv(s2e9Posafinn, file = "top-ten/season2/Posafinns2e9.csv")
write.csv(s2e10Posafinn, file = "top-ten/season2/Posafinns2e10.csv")
write.csv(s2e11Posafinn, file = "top-ten/season2/Posafinns2e11.csv")
write.csv(s2e12Posafinn, file = "top-ten/season2/Posafinns2e12.csv")
write.csv(s2e13Posafinn, file = "top-ten/season2/Posafinns2e13.csv")
write.csv(s2e14Posafinn, file = "top-ten/season2/Posafinns2e14.csv")
write.csv(s2e15Posafinn, file = "top-ten/season2/Posafinns2e15.csv")
write.csv(s2e16Posafinn, file = "top-ten/season2/Posafinns2e16.csv")
write.csv(s2e17Posafinn, file = "top-ten/season2/Posafinns2e17.csv")
write.csv(s2e18Posafinn, file = "top-ten/season2/Posafinns2e18.csv")
write.csv(s2e19Posafinn, file = "top-ten/season2/Posafinns2e19.csv")
write.csv(s2e20Posafinn, file = "top-ten/season2/Posafinns2e20.csv")
write.csv(s2e21Posafinn, file = "top-ten/season2/Posafinns2e21.csv")
write.csv(s2e22Posafinn, file = "top-ten/season2/Posafinns2e22.csv")
# Negatives
write.csv(s2e1Negafinn, file = "top-ten/season2/Negafinns2e1.csv")
write.csv(s2e2Negafinn, file = "top-ten/season2/Negafinns2e2.csv")
write.csv(s2e3Negafinn, file = "top-ten/season2/Negafinns2e3.csv")
write.csv(s2e4Negafinn, file = "top-ten/season2/Negafinns2e4.csv")
write.csv(s2e5Negafinn, file = "top-ten/season2/Negafinns2e5.csv")
write.csv(s2e6Negafinn, file = "top-ten/season2/Negafinns2e6.csv")
write.csv(s2e7Negafinn, file = "top-ten/season2/Negafinns2e7.csv")
write.csv(s2e8Negafinn, file = "top-ten/season2/Negafinns2e8.csv")
write.csv(s2e9Negafinn, file = "top-ten/season2/Negafinns2e9.csv")
write.csv(s2e10Negafinn, file = "top-ten/season2/Negafinns2e10.csv")
write.csv(s2e11Negafinn, file = "top-ten/season2/Negafinns2e11.csv")
write.csv(s2e12Negafinn, file = "top-ten/season2/Negafinns2e12.csv")
write.csv(s2e13Negafinn, file = "top-ten/season2/Negafinns2e13.csv")
write.csv(s2e14Negafinn, file = "top-ten/season2/Negafinns2e14.csv")
write.csv(s2e15Negafinn, file = "top-ten/season2/Negafinns2e15.csv")
write.csv(s2e16Negafinn, file = "top-ten/season2/Negafinns2e16.csv")
write.csv(s2e17Negafinn, file = "top-ten/season2/Negafinns2e17.csv")
write.csv(s2e18Negafinn, file = "top-ten/season2/Negafinns2e18.csv")
write.csv(s2e19Negafinn, file = "top-ten/season2/Negafinns2e19.csv")
write.csv(s2e20Negafinn, file = "top-ten/season2/Negafinns2e20.csv")
write.csv(s2e21Negafinn, file = "top-ten/season2/Negafinns2e21.csv")
write.csv(s2e22Negafinn, file = "top-ten/season2/Negafinns2e22.csv")
## bing
write.csv(s2e1Posbing, file = "top-ten/season2/Posbings2e1.csv")
write.csv(s2e2Posbing, file = "top-ten/season2/Posbings2e2.csv")
write.csv(s2e3Posbing, file = "top-ten/season2/Posbings2e3.csv")
write.csv(s2e4Posbing, file = "top-ten/season2/Posbings2e4.csv")
write.csv(s2e5Posbing, file = "top-ten/season2/Posbings2e5.csv")
write.csv(s2e6Posbing, file = "top-ten/season2/Posbings2e6.csv")
write.csv(s2e7Posbing, file = "top-ten/season2/Posbings2e7.csv")
write.csv(s2e8Posbing, file = "top-ten/season2/Posbings2e8.csv")
write.csv(s2e9Posbing, file = "top-ten/season2/Posbings2e9.csv")
write.csv(s2e10Posbing, file = "top-ten/season2/Posbings2e10.csv")
write.csv(s2e11Posbing, file = "top-ten/season2/Posbings2e11.csv")
write.csv(s2e12Posbing, file = "top-ten/season2/Posbings2e12.csv")
write.csv(s2e13Posbing, file = "top-ten/season2/Posbings2e13.csv")
write.csv(s2e14Posbing, file = "top-ten/season2/Posbings2e14.csv")
write.csv(s2e15Posbing, file = "top-ten/season2/Posbings2e15.csv")
write.csv(s2e16Posbing, file = "top-ten/season2/Posbings2e16.csv")
write.csv(s2e17Posbing, file = "top-ten/season2/Posbings2e17.csv")
write.csv(s2e18Posbing, file = "top-ten/season2/Posbings2e18.csv")
write.csv(s2e19Posbing, file = "top-ten/season2/Posbings2e19.csv")
write.csv(s2e20Posbing, file = "top-ten/season2/Posbings2e20.csv")
write.csv(s2e21Posbing, file = "top-ten/season2/Posbings2e21.csv")
write.csv(s2e22Posbing, file = "top-ten/season2/Posbings2e22.csv")
# Negatives
write.csv(s2e1Negbing, file = "top-ten/season2/Negbings2e1.csv")
write.csv(s2e2Negbing, file = "top-ten/season2/Negbings2e2.csv")
write.csv(s2e3Negbing, file = "top-ten/season2/Negbings2e3.csv")
write.csv(s2e4Negbing, file = "top-ten/season2/Negbings2e4.csv")
write.csv(s2e5Negbing, file = "top-ten/season2/Negbings2e5.csv")
write.csv(s2e6Negbing, file = "top-ten/season2/Negbings2e6.csv")
write.csv(s2e7Negbing, file = "top-ten/season2/Negbings2e7.csv")
write.csv(s2e8Negbing, file = "top-ten/season2/Negbings2e8.csv")
write.csv(s2e9Negbing, file = "top-ten/season2/Negbings2e9.csv")
write.csv(s2e10Negbing, file = "top-ten/season2/Negbings2e10.csv")
write.csv(s2e11Negbing, file = "top-ten/season2/Negbings2e11.csv")
write.csv(s2e12Negbing, file = "top-ten/season2/Negbings2e12.csv")
write.csv(s2e13Negbing, file = "top-ten/season2/Negbings2e13.csv")
write.csv(s2e14Negbing, file = "top-ten/season2/Negbings2e14.csv")
write.csv(s2e15Negbing, file = "top-ten/season2/Negbings2e15.csv")
write.csv(s2e16Negbing, file = "top-ten/season2/Negbings2e16.csv")
write.csv(s2e17Negbing, file = "top-ten/season2/Negbings2e17.csv")
write.csv(s2e18Negbing, file = "top-ten/season2/Negbings2e18.csv")
write.csv(s2e19Negbing, file = "top-ten/season2/Negbings2e19.csv")
write.csv(s2e20Negbing, file = "top-ten/season2/Negbings2e20.csv")
write.csv(s2e21Negbing, file = "top-ten/season2/Negbings2e21.csv")
write.csv(s2e22Negbing, file = "top-ten/season2/Negbings2e22.csv")

## Bind Season 3
seasonThree <- bind_rows(TokenS3E1,TokenS3E2,TokenS3E3,TokenS3E4,TokenS3E5,TokenS3E6,TokenS3E7,TokenS3E8,TokenS3E9,TokenS3E10,TokenS3E11,TokenS3E12,TokenS3E13,TokenS3E14,TokenS3E15,TokenS3E16,TokenS3E17,TokenS3E18)
## Positive Words, with value and count
affinPosS3 <- seasonThree %>% inner_join(get_sentiments('afinn')) %>%
  count(word, value, sort = TRUE) %>% ungroup() %>% filter(value >= 1)
## Negative Words, with value and count
affinNegS3 <- seasonThree %>% inner_join(get_sentiments('afinn')) %>%
  count(word, value, sort = TRUE) %>% ungroup() %>% filter(value <= -1)
## Count the bing words.
countBingS3 <- seasonThree %>% inner_join(get_sentiments('bing')) %>%
  count(word, sentiment, sort = TRUE) %>% ungroup()
## Save them both out
write.csv(affinPosS3, file = "top-ten/#APS3.csv")
write.csv(affinNegS3, file = "top-ten/#ANS3.csv")
write.csv(countBingS3, file = "top-ten/#BS3.csv")