## Load Libraries
library(dplyr)
library(tidytext)
library(tidyverse)
library(tidyr)
library(stringr)
library(readr)
## Season 1
## Import Datasets
s1e1 <- read.csv("s1e1-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e2 <- read.csv("s1e2-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e3 <- read.csv("s1e3-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e4 <- read.csv("s1e4-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e5 <- read.csv("s1e5-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e6 <- read.csv("s1e6-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e7 <- read.csv("s1e7-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e8 <- read.csv("s1e8-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)

## create a tibble with the Episode ([,1]) & Words ([,2])
tibs1e1 <- tibble(Episode = s1e1[,1], Words = s1e1[,2])
tibs1e2 <- tibble(Episode = s1e2[,1], Words = s1e2[,2])
tibs1e3 <- tibble(Episode = s1e3[,1], Words = s1e3[,2])
tibs1e4 <- tibble(Episode = s1e4[,1], Words = s1e4[,2])
tibs1e5 <- tibble(Episode = s1e5[,1], Words = s1e5[,2])
tibs1e6 <- tibble(Episode = s1e6[,1], Words = s1e6[,2])
tibs1e7 <- tibble(Episode = s1e7[,1], Words = s1e7[,2])
tibs1e8 <- tibble(Episode = s1e8[,1], Words = s1e8[,2])

## Use Inner_Join with afinn
afinns1e1 <- tibs1e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns1e2 <- tibs1e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns1e3 <- tibs1e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns1e4 <- tibs1e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns1e5 <- tibs1e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns1e6 <- tibs1e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns1e7 <- tibs1e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns1e8 <- tibs1e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))

## Look at Loughran example 
## loughran <- tibs1e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("loughran"))
## Look at nrc example
## nrc <- tibs1e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("nrc"))

## Use Dictionary bing
bings1e1 <- tibs1e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings1e2 <- tibs1e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings1e3 <- tibs1e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings1e4 <- tibs1e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings1e5 <- tibs1e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings1e6 <- tibs1e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings1e7 <- tibs1e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings1e8 <- tibs1e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
## Count afinn
countafinns1e1 <- count(afinns1e1, vars = "Episode")
countafinns1e2 <- count(afinns1e2, vars = "Episode")
countafinns1e3 <- count(afinns1e3, vars = "Episode")
countafinns1e4 <- count(afinns1e4, vars = "Episode")
countafinns1e5 <- count(afinns1e5, vars = "Episode")
countafinns1e6 <- count(afinns1e6, vars = "Episode")
countafinns1e7 <- count(afinns1e7, vars = "Episode")
countafinns1e8 <- count(afinns1e8, vars = "Episode")
## Count bing
countbings1e1 <- count(bings1e1, vars = "Episode")
countbings1e2 <- count(bings1e2, vars = "Episode")
countbings1e3 <- count(bings1e3, vars = "Episode")
countbings1e4 <- count(bings1e4, vars = "Episode")
countbings1e5 <- count(bings1e5, vars = "Episode")
countbings1e6 <- count(bings1e6, vars = "Episode")
countbings1e7 <- count(bings1e7, vars = "Episode")
countbings1e8 <- count(bings1e8, vars = "Episode")
## POSITIVES
## afinn Filter Positive
positiveafinns1e1 <- afinns1e1 %>% filter(value >= 0)
positiveafinns1e2 <- afinns1e2 %>% filter(value >= 0)
positiveafinns1e3 <- afinns1e3 %>% filter(value >= 0)
positiveafinns1e4 <- afinns1e4 %>% filter(value >= 0)
positiveafinns1e5 <- afinns1e5 %>% filter(value >= 0)
positiveafinns1e6 <- afinns1e6 %>% filter(value >= 0)
positiveafinns1e7 <- afinns1e7 %>% filter(value >= 0)
positiveafinns1e8 <- afinns1e8 %>% filter(value >= 0)
## bing Filter Positive
positivebings1e1 <- bings1e1 %>% filter(sentiment == 'positive')
positivebings1e2 <- bings1e2 %>% filter(sentiment == 'positive')
positivebings1e3 <- bings1e3 %>% filter(sentiment == 'positive')
positivebings1e4 <- bings1e4 %>% filter(sentiment == 'positive')
positivebings1e5 <- bings1e5 %>% filter(sentiment == 'positive')
positivebings1e6 <- bings1e6 %>% filter(sentiment == 'positive')
positivebings1e7 <- bings1e7 %>% filter(sentiment == 'positive')
positivebings1e8 <- bings1e8 %>% filter(sentiment == 'positive')
## afinn Count Positives
countPAs1e1 <- count(positiveafinns1e1, vars = "Episode")
countPAs1e2 <- count(positiveafinns1e2, vars = "Episode")
countPAs1e3 <- count(positiveafinns1e3, vars = "Episode")
countPAs1e4 <- count(positiveafinns1e4, vars = "Episode")
countPAs1e5 <- count(positiveafinns1e5, vars = "Episode")
countPAs1e6 <- count(positiveafinns1e6, vars = "Episode")
countPAs1e7 <- count(positiveafinns1e7, vars = "Episode")
countPAs1e8 <- count(positiveafinns1e8, vars = "Episode")
## bing Count Positives
countPBs1e1 <- count(positivebings1e1, vars = "Episode")
countPBs1e2 <- count(positivebings1e2, vars = "Episode")
countPBs1e3 <- count(positivebings1e3, vars = "Episode")
countPBs1e4 <- count(positivebings1e4, vars = "Episode")
countPBs1e5 <- count(positivebings1e5, vars = "Episode")
countPBs1e6 <- count(positivebings1e6, vars = "Episode")
countPBs1e7 <- count(positivebings1e7, vars = "Episode")
countPBs1e8 <- count(positivebings1e8, vars = "Episode")
## NEGATIVES
## afinn Filter Negative
negativeafinns1e1 <- afinns1e1 %>% filter(value <= 0)
negativeafinns1e2 <- afinns1e2 %>% filter(value <= 0)
negativeafinns1e3 <- afinns1e3 %>% filter(value <= 0)
negativeafinns1e4 <- afinns1e4 %>% filter(value <= 0)
negativeafinns1e5 <- afinns1e5 %>% filter(value <= 0)
negativeafinns1e6 <- afinns1e6 %>% filter(value <= 0)
negativeafinns1e7 <- afinns1e7 %>% filter(value <= 0)
negativeafinns1e8 <- afinns1e8 %>% filter(value <= 0)
## bing Filter Negative
negativebings1e1 <- bings1e1 %>% filter(sentiment == 'negative')
negativebings1e2 <- bings1e2 %>% filter(sentiment == 'negative')
negativebings1e3 <- bings1e3 %>% filter(sentiment == 'negative')
negativebings1e4 <- bings1e4 %>% filter(sentiment == 'negative')
negativebings1e5 <- bings1e5 %>% filter(sentiment == 'negative')
negativebings1e6 <- bings1e6 %>% filter(sentiment == 'negative')
negativebings1e7 <- bings1e7 %>% filter(sentiment == 'negative')
negativebings1e8 <- bings1e8 %>% filter(sentiment == 'negative')
## afinn Count Negatives
countNAs1e1 <- count(negativeafinns1e1, vars = "Episode")
countNAs1e2 <- count(negativeafinns1e2, vars = "Episode")
countNAs1e3 <- count(negativeafinns1e3, vars = "Episode")
countNAs1e4 <- count(negativeafinns1e4, vars = "Episode")
countNAs1e5 <- count(negativeafinns1e5, vars = "Episode")
countNAs1e6 <- count(negativeafinns1e6, vars = "Episode")
countNAs1e7 <- count(negativeafinns1e7, vars = "Episode")
countNAs1e8 <- count(negativeafinns1e8, vars = "Episode")
## bing Count Negatives
countNBs1e1 <- count(negativebings1e1, vars = "Episode")
countNBs1e2 <- count(negativebings1e2, vars = "Episode")
countNBs1e3 <- count(negativebings1e3, vars = "Episode")
countNBs1e4 <- count(negativebings1e4, vars = "Episode")
countNBs1e5 <- count(negativebings1e5, vars = "Episode")
countNBs1e6 <- count(negativebings1e6, vars = "Episode")
countNBs1e7 <- count(negativebings1e7, vars = "Episode")
countNBs1e8 <- count(negativebings1e8, vars = "Episode")
## Top 10 Positive words
## afinn
s1e1PosAfinn <- positiveAfinns1e1 %>% count(word) %>% arrange(desc(n))
s1e2PosAfinn <- positiveAfinns1e2 %>% count(word) %>% arrange(desc(n))
s1e3PosAfinn <- positiveAfinns1e3 %>% count(word) %>% arrange(desc(n))
s1e4PosAfinn <- positiveAfinns1e4 %>% count(word) %>% arrange(desc(n))
s1e5PosAfinn <- positiveAfinns1e5 %>% count(word) %>% arrange(desc(n))
s1e6PosAfinn <- positiveAfinns1e6 %>% count(word) %>% arrange(desc(n))
s1e7PosAfinn <- positiveAfinns1e7 %>% count(word) %>% arrange(desc(n))
s1e8PosAfinn <- positiveAfinns1e8 %>% count(word) %>% arrange(desc(n))
## bing
s1e1PosBing <- positiveBings1e1 %>% count(word) %>% arrange(desc(n))
s1e2PosBing <- positiveBings1e2 %>% count(word) %>% arrange(desc(n))
s1e3PosBing <- positiveBings1e3 %>% count(word) %>% arrange(desc(n))
s1e4PosBing <- positiveBings1e4 %>% count(word) %>% arrange(desc(n))
s1e5PosBing <- positiveBings1e5 %>% count(word) %>% arrange(desc(n))
s1e6PosBing <- positiveBings1e6 %>% count(word) %>% arrange(desc(n))
s1e7PosBing <- positiveBings1e7 %>% count(word) %>% arrange(desc(n))
s1e8PosBing <- positiveBings1e8 %>% count(word) %>% arrange(desc(n))
## Top 10 Negative words
## afinn
s1e1NegAfinn <- negativeAfinns1e1 %>% count(word) %>% arrange(desc(n))
s1e2NegAfinn <- negativeAfinns1e2 %>% count(word) %>% arrange(desc(n))
s1e3NegAfinn <- negativeAfinns1e3 %>% count(word) %>% arrange(desc(n))
s1e4NegAfinn <- negativeAfinns1e4 %>% count(word) %>% arrange(desc(n))
s1e5NegAfinn <- negativeAfinns1e5 %>% count(word) %>% arrange(desc(n))
s1e6NegAfinn <- negativeAfinns1e6 %>% count(word) %>% arrange(desc(n))
s1e7NegAfinn <- negativeAfinns1e7 %>% count(word) %>% arrange(desc(n))
s1e8NegAfinn <- negativeAfinns1e8 %>% count(word) %>% arrange(desc(n))
## bing
s1e1NegBing <- negativeBings1e1 %>% count(word) %>% arrange(desc(n))
s1e2NegBing <- negativeBings1e2 %>% count(word) %>% arrange(desc(n))
s1e3NegBing <- negativeBings1e3 %>% count(word) %>% arrange(desc(n))
s1e4NegBing <- negativeBings1e4 %>% count(word) %>% arrange(desc(n))
s1e5NegBing <- negativeBings1e5 %>% count(word) %>% arrange(desc(n))
s1e6NegBing <- negativeBings1e6 %>% count(word) %>% arrange(desc(n))
s1e7NegBing <- negativeBings1e7 %>% count(word) %>% arrange(desc(n))
s1e8NegBing <- negativeBings1e8 %>% count(word) %>% arrange(desc(n))

## Save Season 1 Afinns
# Positive
write.csv(s1e1PosAfinn, file = "top-ten/PosAfinns1e1.csv")
write.csv(s1e2PosAfinn, file = "top-ten/PosAfinns1e2.csv")
write.csv(s1e3PosAfinn, file = "top-ten/PosAfinns1e3.csv")
write.csv(s1e4PosAfinn, file = "top-ten/PosAfinns1e4.csv")
write.csv(s1e5PosAfinn, file = "top-ten/PosAfinns1e5.csv")
write.csv(s1e6PosAfinn, file = "top-ten/PosAfinns1e6.csv")
write.csv(s1e7PosAfinn, file = "top-ten/PosAfinns1e7.csv")
write.csv(s1e8PosAfinn, file = "top-ten/PosAfinns1e8.csv")
# Negative
write.csv(s1e1NegAfinn, file = "top-ten/NegAfinns1e1.csv")
write.csv(s1e2NegAfinn, file = "top-ten/NegAfinns1e2.csv")
write.csv(s1e3NegAfinn, file = "top-ten/NegAfinns1e3.csv")
write.csv(s1e4NegAfinn, file = "top-ten/NegAfinns1e4.csv")
write.csv(s1e5NegAfinn, file = "top-ten/NegAfinns1e5.csv")
write.csv(s1e6NegAfinn, file = "top-ten/NegAfinns1e6.csv")
write.csv(s1e7NegAfinn, file = "top-ten/NegAfinns1e7.csv")
write.csv(s1e8NegAfinn, file = "top-ten/NegAfinns1e8.csv")
## Save Season 1 Bings
# Positive
write.csv(s1e1PosBing, file = "top-ten/PosBings1e1.csv")
write.csv(s1e2PosBing, file = "top-ten/PosBings1e2.csv")
write.csv(s1e3PosBing, file = "top-ten/PosBings1e3.csv")
write.csv(s1e4PosBing, file = "top-ten/PosBings1e4.csv")
write.csv(s1e5PosBing, file = "top-ten/PosBings1e5.csv")
write.csv(s1e6PosBing, file = "top-ten/PosBings1e6.csv")
write.csv(s1e7PosBing, file = "top-ten/PosBings1e7.csv")
write.csv(s1e8PosBing, file = "top-ten/PosBings1e8.csv")
# Negative
write.csv(s1e1NegBing, file = "top-ten/NegBings1e1.csv")
write.csv(s1e2NegBing, file = "top-ten/NegBings1e2.csv")
write.csv(s1e3NegBing, file = "top-ten/NegBings1e3.csv")
write.csv(s1e4NegBing, file = "top-ten/NegBings1e4.csv")
write.csv(s1e5NegBing, file = "top-ten/NegBings1e5.csv")
write.csv(s1e6NegBing, file = "top-ten/NegBings1e6.csv")
write.csv(s1e7NegBing, file = "top-ten/NegBings1e7.csv")
write.csv(s1e8NegBing, file = "top-ten/NegBings1e8.csv")

## Season 2
## Import Datasets
s2e1 <- read.csv("s2e1-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e2 <- read.csv("s2e2-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e3 <- read.csv("s2e3-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e4 <- read.csv("s2e4-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e5 <- read.csv("s2e5-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e6 <- read.csv("s2e6-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e7 <- read.csv("s2e7-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e8 <- read.csv("s2e8-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e9 <- read.csv("s2e9-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e10 <- read.csv("s2e10-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e11 <- read.csv("s2e11-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e12 <- read.csv("s2e12-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e13 <- read.csv("s2e13-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e14 <- read.csv("s2e14-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e15 <- read.csv("s2e15-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e16 <- read.csv("s2e16-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e17 <- read.csv("s2e17-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e18 <- read.csv("s2e18-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e19 <- read.csv("s2e19-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e20 <- read.csv("s2e20-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e21 <- read.csv("s2e21-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e22 <- read.csv("s2e22-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
## create a tibble with the Episode ([,1]) & Words ([,2])
tibs2e1 <- tibble(Episode = s2e1[,1], Words = s2e1[,2])
tibs2e2 <- tibble(Episode = s2e2[,1], Words = s2e2[,2])
tibs2e3 <- tibble(Episode = s2e3[,1], Words = s2e3[,2])
tibs2e4 <- tibble(Episode = s2e4[,1], Words = s2e4[,2])
tibs2e5 <- tibble(Episode = s2e5[,1], Words = s2e5[,2])
tibs2e6 <- tibble(Episode = s2e6[,1], Words = s2e6[,2])
tibs2e7 <- tibble(Episode = s2e7[,1], Words = s2e7[,2])
tibs2e8 <- tibble(Episode = s2e8[,1], Words = s2e8[,2])
tibs2e9 <- tibble(Episode = s2e9[,1], Words = s2e9[,2])
tibs2e10 <- tibble(Episode = s2e10[,1], Words = s2e10[,2])
tibs2e11 <- tibble(Episode = s2e11[,1], Words = s2e11[,2])
tibs2e12 <- tibble(Episode = s2e12[,1], Words = s2e12[,2])
tibs2e13 <- tibble(Episode = s2e13[,1], Words = s2e13[,2])
tibs2e14 <- tibble(Episode = s2e14[,1], Words = s2e14[,2])
tibs2e15 <- tibble(Episode = s2e15[,1], Words = s2e15[,2])
tibs2e16 <- tibble(Episode = s2e16[,1], Words = s2e16[,2])
tibs2e17 <- tibble(Episode = s2e17[,1], Words = s2e17[,2])
tibs2e18 <- tibble(Episode = s2e18[,1], Words = s2e18[,2])
tibs2e19 <- tibble(Episode = s2e19[,1], Words = s2e19[,2])
tibs2e20 <- tibble(Episode = s2e20[,1], Words = s2e20[,2])
tibs2e21 <- tibble(Episode = s2e21[,1], Words = s2e21[,2])
tibs2e22 <- tibble(Episode = s2e22[,1], Words = s2e22[,2])
## afinn
afinns2e1 <- tibs2e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e2 <- tibs2e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e3 <- tibs2e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e4 <- tibs2e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e5 <- tibs2e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e6 <- tibs2e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e7 <- tibs2e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e8 <- tibs2e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e9 <- tibs2e9 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e10 <- tibs2e10 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e11 <- tibs2e11 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e12 <- tibs2e12 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e13 <- tibs2e13 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e14 <- tibs2e14 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e15 <- tibs2e15 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e16 <- tibs2e16 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e17 <- tibs2e17 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e18 <- tibs2e18 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e19 <- tibs2e19 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e20 <- tibs2e20 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e21 <- tibs2e21 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns2e22 <- tibs2e22 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
## bing
bings2e1 <- tibs2e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e2 <- tibs2e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e3 <- tibs2e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e4 <- tibs2e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e5 <- tibs2e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e6 <- tibs2e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e7 <- tibs2e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e8 <- tibs2e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e9 <- tibs2e9 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e10 <- tibs2e10 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e11 <- tibs2e11 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e12 <- tibs2e12 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e13 <- tibs2e13 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e14 <- tibs2e14 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e15 <- tibs2e15 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e16 <- tibs2e16 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e17 <- tibs2e17 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e18 <- tibs2e18 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e19 <- tibs2e19 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e20 <- tibs2e20 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e21 <- tibs2e21 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings2e22 <- tibs2e22 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
## Count Afinn
countAfinn2e1 <- count(afinns2e1, vars = "Episode")
countAfinn2e2 <- count(afinns2e2, vars = "Episode")
countAfinn2e3 <- count(afinns2e3, vars = "Episode")
countAfinn2e4 <- count(afinns2e4, vars = "Episode")
countAfinn2e5 <- count(afinns2e5, vars = "Episode")
countAfinn2e6 <- count(afinns2e6, vars = "Episode")
countAfinn2e7 <- count(afinns2e7, vars = "Episode")
countAfinn2e8 <- count(afinns2e8, vars = "Episode")
countAfinn2e9 <- count(afinns2e9, vars = "Episode")
countAfinn2e10 <- count(afinns2e10, vars = "Episode")
countAfinn2e11 <- count(afinns2e11, vars = "Episode")
countAfinn2e12 <- count(afinns2e12, vars = "Episode")
countAfinn2e13 <- count(afinns2e13, vars = "Episode")
countAfinn2e14 <- count(afinns2e14, vars = "Episode")
countAfinn2e15 <- count(afinns2e15, vars = "Episode")
countAfinn2e16 <- count(afinns2e16, vars = "Episode")
countAfinn2e17 <- count(afinns2e17, vars = "Episode")
countAfinn2e18 <- count(afinns2e18, vars = "Episode")
countAfinn2e19 <- count(afinns2e19, vars = "Episode")
countAfinn2e20 <- count(afinns2e20, vars = "Episode")
countAfinn2e21 <- count(afinns2e21, vars = "Episode")
countAfinn2e22 <- count(afinns2e22, vars = "Episode")
## Count bing
countbings2e1 <- count(bings2e1, vars = "Episode")
countbings2e2 <- count(bings2e2, vars = "Episode")
countbings2e3 <- count(bings2e3, vars = "Episode")
countbings2e4 <- count(bings2e4, vars = "Episode")
countbings2e5 <- count(bings2e5, vars = "Episode")
countbings2e6 <- count(bings2e6, vars = "Episode")
countbings2e7 <- count(bings2e7, vars = "Episode")
countbings2e8 <- count(bings2e8, vars = "Episode")
countbings2e9 <- count(bings2e9, vars = "Episode")
countbings2e10 <- count(bings2e10, vars = "Episode")
countbings2e11 <- count(bings2e11, vars = "Episode")
countbings2e12 <- count(bings2e12, vars = "Episode")
countbings2e13 <- count(bings2e13, vars = "Episode")
countbings2e14 <- count(bings2e14, vars = "Episode")
countbings2e15 <- count(bings2e15, vars = "Episode")
countbings2e16 <- count(bings2e16, vars = "Episode")
countbings2e17 <- count(bings2e17, vars = "Episode")
countbings2e18 <- count(bings2e18, vars = "Episode")
countbings2e19 <- count(bings2e19, vars = "Episode")
countbings2e20 <- count(bings2e20, vars = "Episode")
countbings2e21 <- count(bings2e21, vars = "Episode")
countbings2e22 <- count(bings2e22, vars = "Episode")
## afinn filter positive
positiveafinns2e1 <-  afinns2e1 %>% filter(value >= 0)
positiveafinns2e2 <-  afinns2e2 %>% filter(value >= 0)
positiveafinns2e3 <-  afinns2e3 %>% filter(value >= 0)
positiveafinns2e4 <-  afinns2e4 %>% filter(value >= 0)
positiveafinns2e5 <-  afinns2e5 %>% filter(value >= 0)
positiveafinns2e6 <-  afinns2e6 %>% filter(value >= 0)
positiveafinns2e7 <-  afinns2e7 %>% filter(value >= 0)
positiveafinns2e8 <-  afinns2e8 %>% filter(value >= 0)
positiveafinns2e9 <-  afinns2e9 %>% filter(value >= 0)
positiveafinns2e10 <- afinns2e10 %>% filter(value >= 0)
positiveafinns2e11 <- afinns2e11 %>% filter(value >= 0)
positiveafinns2e12 <- afinns2e12 %>% filter(value >= 0)
positiveafinns2e13 <- afinns2e13 %>% filter(value >= 0)
positiveafinns2e14 <- afinns2e14 %>% filter(value >= 0)
positiveafinns2e15 <- afinns2e15 %>% filter(value >= 0)
positiveafinns2e16 <- afinns2e16 %>% filter(value >= 0)
positiveafinns2e17 <- afinns2e17 %>% filter(value >= 0)
positiveafinns2e18 <- afinns2e18 %>% filter(value >= 0)
positiveafinns2e19 <- afinns2e19 %>% filter(value >= 0)
positiveafinns2e20 <- afinns2e20 %>% filter(value >= 0)
positiveafinns2e21 <- afinns2e21 %>% filter(value >= 0)
positiveafinns2e22 <- afinns2e22 %>% filter(value >= 0)
## bing filter positive bing
positivebings2e1 <-  bings2e1 %>% filter(sentiment == 'positive')
positivebings2e2 <-  bings2e2 %>% filter(sentiment == 'positive')
positivebings2e3 <-  bings2e3 %>% filter(sentiment == 'positive')
positivebings2e4 <-  bings2e4 %>% filter(sentiment == 'positive')
positivebings2e5 <-  bings2e5 %>% filter(sentiment == 'positive')
positivebings2e6 <-  bings2e6 %>% filter(sentiment == 'positive')
positivebings2e7 <-  bings2e7 %>% filter(sentiment == 'positive')
positivebings2e8 <-  bings2e8 %>% filter(sentiment == 'positive')
positivebings2e9 <-  bings2e9 %>% filter(sentiment == 'positive')
positivebings2e10 <- bings2e10 %>% filter(sentiment == 'positive')
positivebings2e11 <- bings2e11 %>% filter(sentiment == 'positive')
positivebings2e12 <- bings2e12 %>% filter(sentiment == 'positive')
positivebings2e13 <- bings2e13 %>% filter(sentiment == 'positive')
positivebings2e14 <- bings2e14 %>% filter(sentiment == 'positive')
positivebings2e15 <- bings2e15 %>% filter(sentiment == 'positive')
positivebings2e16 <- bings2e16 %>% filter(sentiment == 'positive')
positivebings2e17 <- bings2e17 %>% filter(sentiment == 'positive')
positivebings2e18 <- bings2e18 %>% filter(sentiment == 'positive')
positivebings2e19 <- bings2e19 %>% filter(sentiment == 'positive')
positivebings2e20 <- bings2e20 %>% filter(sentiment == 'positive')
positivebings2e21 <- bings2e21 %>% filter(sentiment == 'positive')
positivebings2e22 <- bings2e22 %>% filter(sentiment == 'positive')
## afinn Count Positives
countPAs2e1 <-  count(positiveafinns2e1, vars = "Episode")
countPAs2e2 <-  count(positiveafinns2e2, vars = "Episode")
countPAs2e3 <-  count(positiveafinns2e3, vars = "Episode")
countPAs2e4 <-  count(positiveafinns2e4, vars = "Episode")
countPAs2e5 <-  count(positiveafinns2e5, vars = "Episode")
countPAs2e6 <-  count(positiveafinns2e6, vars = "Episode")
countPAs2e7 <-  count(positiveafinns2e7, vars = "Episode")
countPAs2e8 <-  count(positiveafinns2e8, vars = "Episode")
countPAs2e9 <-  count(positiveafinns2e9, vars = "Episode")
countPAs2e10 <- count(positiveafinns2e10, vars = "Episode")
countPAs2e11 <- count(positiveafinns2e11, vars = "Episode")
countPAs2e12 <- count(positiveafinns2e12, vars = "Episode")
countPAs2e13 <- count(positiveafinns2e13, vars = "Episode")
countPAs2e14 <- count(positiveafinns2e14, vars = "Episode")
countPAs2e15 <- count(positiveafinns2e15, vars = "Episode")
countPAs2e16 <- count(positiveafinns2e16, vars = "Episode")
countPAs2e17 <- count(positiveafinns2e17, vars = "Episode")
countPAs2e18 <- count(positiveafinns2e18, vars = "Episode")
countPAs2e19 <- count(positiveafinns2e19, vars = "Episode")
countPAs2e20 <- count(positiveafinns2e20, vars = "Episode")
countPAs2e21 <- count(positiveafinns2e21, vars = "Episode")
countPAs2e22 <- count(positiveafinns2e22, vars = "Episode")
## bing Count Positives
countPBs2e1 <-  count(positivebings2e1, vars = "Episode")
countPBs2e2 <-  count(positivebings2e2, vars = "Episode")
countPBs2e3 <-  count(positivebings2e3, vars = "Episode")
countPBs2e4 <-  count(positivebings2e4, vars = "Episode")
countPBs2e5 <-  count(positivebings2e5, vars = "Episode")
countPBs2e6 <-  count(positivebings2e6, vars = "Episode")
countPBs2e7 <-  count(positivebings2e7, vars = "Episode")
countPBs2e8 <-  count(positivebings2e8, vars = "Episode")
countPBs2e9 <-  count(positivebings2e9, vars = "Episode")
countPBs2e10 <- count(positivebings2e10, vars = "Episode")
countPBs2e11 <- count(positivebings2e11, vars = "Episode")
countPBs2e12 <- count(positivebings2e12, vars = "Episode")
countPBs2e13 <- count(positivebings2e13, vars = "Episode")
countPBs2e14 <- count(positivebings2e14, vars = "Episode")
countPBs2e15 <- count(positivebings2e15, vars = "Episode")
countPBs2e16 <- count(positivebings2e16, vars = "Episode")
countPBs2e17 <- count(positivebings2e17, vars = "Episode")
countPBs2e18 <- count(positivebings2e18, vars = "Episode")
countPBs2e19 <- count(positivebings2e19, vars = "Episode")
countPBs2e20 <- count(positivebings2e20, vars = "Episode")
countPBs2e21 <- count(positivebings2e21, vars = "Episode")
countPBs2e22 <- count(positivebings2e22, vars = "Episode")
## afinn Filter Negative
negativeafinns2e1 <-  afinns2e1 %>% filter(value  <= 0)
negativeafinns2e2 <-  afinns2e2 %>% filter(value  <= 0)
negativeafinns2e3 <-  afinns2e3 %>% filter(value  <= 0)
negativeafinns2e4 <-  afinns2e4 %>% filter(value  <= 0)
negativeafinns2e5 <-  afinns2e5 %>% filter(value  <= 0)
negativeafinns2e6 <-  afinns2e6 %>% filter(value  <= 0)
negativeafinns2e7 <-  afinns2e7 %>% filter(value  <= 0)
negativeafinns2e8 <-  afinns2e8 %>% filter(value  <= 0)
negativeafinns2e9 <-  afinns2e9 %>% filter(value  <= 0)
negativeafinns2e10 <- afinns2e10 %>% filter(value <= 0)
negativeafinns2e11 <- afinns2e11 %>% filter(value <= 0)
negativeafinns2e12 <- afinns2e12 %>% filter(value <= 0)
negativeafinns2e13 <- afinns2e13 %>% filter(value <= 0)
negativeafinns2e14 <- afinns2e14 %>% filter(value <= 0)
negativeafinns2e15 <- afinns2e15 %>% filter(value <= 0)
negativeafinns2e16 <- afinns2e16 %>% filter(value <= 0)
negativeafinns2e17 <- afinns2e17 %>% filter(value <= 0)
negativeafinns2e18 <- afinns2e18 %>% filter(value <= 0)
negativeafinns2e19 <- afinns2e19 %>% filter(value <= 0)
negativeafinns2e20 <- afinns2e20 %>% filter(value <= 0)
negativeafinns2e21 <- afinns2e21 %>% filter(value <= 0)
negativeafinns2e22 <- afinns2e22 %>% filter(value <= 0)
## bing Filter Negative
negativebings2e1 <-  bings2e1 %>% filter(sentiment == 'negative')
negativebings2e2 <-  bings2e2 %>% filter(sentiment == 'negative')
negativebings2e3 <-  bings2e3 %>% filter(sentiment == 'negative')
negativebings2e4 <-  bings2e4 %>% filter(sentiment == 'negative')
negativebings2e5 <-  bings2e5 %>% filter(sentiment == 'negative')
negativebings2e6 <-  bings2e6 %>% filter(sentiment == 'negative')
negativebings2e7 <-  bings2e7 %>% filter(sentiment == 'negative')
negativebings2e8 <-  bings2e8 %>% filter(sentiment == 'negative')
negativebings2e9 <-  bings2e9 %>% filter(sentiment == 'negative')
negativebings2e10 <- bings2e10 %>% filter(sentiment == 'negative')
negativebings2e11 <- bings2e11 %>% filter(sentiment == 'negative')
negativebings2e12 <- bings2e12 %>% filter(sentiment == 'negative')
negativebings2e13 <- bings2e13 %>% filter(sentiment == 'negative')
negativebings2e14 <- bings2e14 %>% filter(sentiment == 'negative')
negativebings2e15 <- bings2e15 %>% filter(sentiment == 'negative')
negativebings2e16 <- bings2e16 %>% filter(sentiment == 'negative')
negativebings2e17 <- bings2e17 %>% filter(sentiment == 'negative')
negativebings2e18 <- bings2e18 %>% filter(sentiment == 'negative')
negativebings2e19 <- bings2e19 %>% filter(sentiment == 'negative')
negativebings2e20 <- bings2e20 %>% filter(sentiment == 'negative')
negativebings2e21 <- bings2e21 %>% filter(sentiment == 'negative')
negativebings2e22 <- bings2e22 %>% filter(sentiment == 'negative')
## afinn Count Negatives
countNAs2e1 <-  count(negativeafinns2e1, vars = "Episode")
countNAs2e2 <-  count(negativeafinns2e2, vars = "Episode")
countNAs2e3 <-  count(negativeafinns2e3, vars = "Episode")
countNAs2e4 <-  count(negativeafinns2e4, vars = "Episode")
countNAs2e5 <-  count(negativeafinns2e5, vars = "Episode")
countNAs2e6 <-  count(negativeafinns2e6, vars = "Episode")
countNAs2e7 <-  count(negativeafinns2e7, vars = "Episode")
countNAs2e8 <-  count(negativeafinns2e8, vars = "Episode")
countNAs2e9 <-  count(negativeafinns2e9, vars = "Episode")
countNAs2e10 <- count(negativeafinns2e10, vars = "Episode")
countNAs2e11 <- count(negativeafinns2e11, vars = "Episode")
countNAs2e12 <- count(negativeafinns2e12, vars = "Episode")
countNAs2e13 <- count(negativeafinns2e13, vars = "Episode")
countNAs2e14 <- count(negativeafinns2e14, vars = "Episode")
countNAs2e15 <- count(negativeafinns2e15, vars = "Episode")
countNAs2e16 <- count(negativeafinns2e16, vars = "Episode")
countNAs2e17 <- count(negativeafinns2e17, vars = "Episode")
countNAs2e18 <- count(negativeafinns2e18, vars = "Episode")
countNAs2e19 <- count(negativeafinns2e19, vars = "Episode")
countNAs2e20 <- count(negativeafinns2e20, vars = "Episode")
countNAs2e21 <- count(negativeafinns2e21, vars = "Episode")
countNAs2e22 <- count(negativeafinns2e22, vars = "Episode")
## bing Count Negatives
countNBs2e1 <-  count(negativebings2e1, vars = "Episode")
countNBs2e2 <-  count(negativebings2e2, vars = "Episode")
countNBs2e3 <-  count(negativebings2e3, vars = "Episode")
countNBs2e4 <-  count(negativebings2e4, vars = "Episode")
countNBs2e5 <-  count(negativebings2e5, vars = "Episode")
countNBs2e6 <-  count(negativebings2e6, vars = "Episode")
countNBs2e7 <-  count(negativebings2e7, vars = "Episode")
countNBs2e8 <-  count(negativebings2e8, vars = "Episode")
countNBs2e9 <-  count(negativebings2e9, vars = "Episode")
countNBs2e10 <- count(negativebings2e10, vars = "Episode")
countNBs2e11 <- count(negativebings2e11, vars = "Episode")
countNBs2e12 <- count(negativebings2e12, vars = "Episode")
countNBs2e13 <- count(negativebings2e13, vars = "Episode")
countNBs2e14 <- count(negativebings2e14, vars = "Episode")
countNBs2e15 <- count(negativebings2e15, vars = "Episode")
countNBs2e16 <- count(negativebings2e16, vars = "Episode")
countNBs2e17 <- count(negativebings2e17, vars = "Episode")
countNBs2e18 <- count(negativebings2e18, vars = "Episode")
countNBs2e19 <- count(negativebings2e19, vars = "Episode")
countNBs2e20 <- count(negativebings2e20, vars = "Episode")
countNBs2e21 <- count(negativebings2e21, vars = "Episode")
countNBs2e22 <- count(negativebings2e22, vars = "Episode")
## Top 10 Positive words
## afinn
s2e1PosAfinn <- positiveafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e2PosAfinn <- positiveafinns2e2 %>% count(word) %>% arrange(desc(n))
s2e3PosAfinn <- positiveafinns2e3 %>% count(word) %>% arrange(desc(n))
s2e4PosAfinn <- positiveafinns2e4 %>% count(word) %>% arrange(desc(n))
s2e5PosAfinn <- positiveafinns2e5 %>% count(word) %>% arrange(desc(n))
s2e6PosAfinn <- positiveafinns2e6 %>% count(word) %>% arrange(desc(n))
s2e7PosAfinn <- positiveafinns2e7 %>% count(word) %>% arrange(desc(n))
s2e8PosAfinn <- positiveafinns2e8 %>% count(word) %>% arrange(desc(n))
s2e9PosAfinn <- positiveafinns2e9 %>% count(word) %>% arrange(desc(n))
s2e10PosAfinn <- positiveafinns2e10 %>% count(word) %>% arrange(desc(n))
s2e11PosAfinn <- positiveafinns2e11 %>% count(word) %>% arrange(desc(n))
s2e12PosAfinn <- positiveafinns2e12 %>% count(word) %>% arrange(desc(n))
s2e13PosAfinn <- positiveafinns2e13 %>% count(word) %>% arrange(desc(n))
s2e14PosAfinn <- positiveafinns2e14 %>% count(word) %>% arrange(desc(n))
s2e15PosAfinn <- positiveafinns2e15 %>% count(word) %>% arrange(desc(n))
s2e16PosAfinn <- positiveafinns2e16 %>% count(word) %>% arrange(desc(n))
s2e17PosAfinn <- positiveafinns2e17 %>% count(word) %>% arrange(desc(n))
s2e18PosAfinn <- positiveafinns2e18 %>% count(word) %>% arrange(desc(n))
s2e19PosAfinn <- positiveafinns2e19 %>% count(word) %>% arrange(desc(n))
s2e20PosAfinn <- positiveafinns2e20 %>% count(word) %>% arrange(desc(n))
s2e21PosAfinn <- positiveafinns2e21 %>% count(word) %>% arrange(desc(n))
s2e22PosAfinn <- positiveafinns2e22 %>% count(word) %>% arrange(desc(n))
# Negatives
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))
s2e1NegAfinn <- negativeafinns2e1 %>% count(word) %>% arrange(desc(n))



## Season 3
## Import Datasets
s3e1 <- read.csv("s3e1-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e2 <- read.csv("s3e2-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e3 <- read.csv("s3e3-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e4 <- read.csv("s3e4-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e5 <- read.csv("s3e5-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e6 <- read.csv("s3e6-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e7 <- read.csv("s3e7-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e8 <- read.csv("s3e8-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e9 <- read.csv("s3e9-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e10 <- read.csv("s3e10-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e11 <- read.csv("s3e11-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e12 <- read.csv("s3e12-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e13 <- read.csv("s3e13-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e14 <- read.csv("s3e14-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e15 <- read.csv("s3e15-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e16 <- read.csv("s3e16-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e17 <- read.csv("s3e17-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s3e18 <- read.csv("s3e18-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
## create a tibble with the Episode ([,1]) & Words ([,2])
tibs3e1 <- tibble(Episode = s3e1[,1], Words = s3e1[,2])
tibs3e2 <- tibble(Episode = s3e2[,1], Words = s3e2[,2])
tibs3e3 <- tibble(Episode = s3e3[,1], Words = s3e3[,2])
tibs3e4 <- tibble(Episode = s3e4[,1], Words = s3e4[,2])
tibs3e5 <- tibble(Episode = s3e5[,1], Words = s3e5[,2])
tibs3e6 <- tibble(Episode = s3e6[,1], Words = s3e6[,2])
tibs3e7 <- tibble(Episode = s3e7[,1], Words = s3e7[,2])
tibs3e8 <- tibble(Episode = s3e8[,1], Words = s3e8[,2])
tibs3e9 <- tibble(Episode = s3e9[,1], Words = s3e9[,2])
tibs3e10 <- tibble(Episode = s3e10[,1], Words = s3e10[,2])
tibs3e11 <- tibble(Episode = s3e11[,1], Words = s3e11[,2])
tibs3e12 <- tibble(Episode = s3e12[,1], Words = s3e12[,2])
tibs3e13 <- tibble(Episode = s3e13[,1], Words = s3e13[,2])
tibs3e14 <- tibble(Episode = s3e14[,1], Words = s3e14[,2])
tibs3e15 <- tibble(Episode = s3e15[,1], Words = s3e15[,2])
tibs3e16 <- tibble(Episode = s3e16[,1], Words = s3e16[,2])
tibs3e17 <- tibble(Episode = s3e17[,1], Words = s3e17[,2])
tibs3e18 <- tibble(Episode = s3e18[,1], Words = s3e18[,2])
## Afinn
afinns3e1 <- tibs3e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e2 <- tibs3e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e3 <- tibs3e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e4 <- tibs3e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e5 <- tibs3e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e6 <- tibs3e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e7 <- tibs3e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e8 <- tibs3e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e9 <- tibs3e9 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e10 <- tibs3e10 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e11 <- tibs3e11 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e12 <- tibs3e12 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e13 <- tibs3e13 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e14 <- tibs3e14 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e15 <- tibs3e15 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e16 <- tibs3e16 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e17 <- tibs3e17 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
afinns3e18 <- tibs3e18 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
## Bing
bings3e1 <- tibs3e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e2 <- tibs3e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e3 <- tibs3e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e4 <- tibs3e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e5 <- tibs3e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e6 <- tibs3e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e7 <- tibs3e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e8 <- tibs3e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e9 <- tibs3e9 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e10 <- tibs3e10 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e11 <- tibs3e11 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e12 <- tibs3e12 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e13 <- tibs3e13 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e14 <- tibs3e14 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e15 <- tibs3e15 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e16 <- tibs3e16 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e17 <- tibs3e17 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
bings3e18 <- tibs3e18 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("bing"))
## afinn Count
countafinns3e1 <- count(afinns3e1, vars = "Episode")
countafinns3e2 <- count(afinns3e2, vars = "Episode")
countafinns3e3 <- count(afinns3e3, vars = "Episode")
countafinns3e4 <- count(afinns3e4, vars = "Episode")
countafinns3e5 <- count(afinns3e5, vars = "Episode")
countafinns3e6 <- count(afinns3e6, vars = "Episode")
countafinns3e7 <- count(afinns3e7, vars = "Episode")
countafinns3e8 <- count(afinns3e8, vars = "Episode")
countafinns3e9 <- count(afinns3e9, vars = "Episode")
countafinns3e10 <- count(afinns3e10, vars = "Episode")
countafinns3e11 <- count(afinns3e11, vars = "Episode")
countafinns3e12 <- count(afinns3e12, vars = "Episode")
countafinns3e13 <- count(afinns3e13, vars = "Episode")
countafinns3e14 <- count(afinns3e14, vars = "Episode")
countafinns3e15 <- count(afinns3e15, vars = "Episode")
countafinns3e16 <- count(afinns3e16, vars = "Episode")
countafinns3e17 <- count(afinns3e17, vars = "Episode")
countafinns3e18 <- count(afinns3e18, vars = "Episode")
## bing Count
countbings3e1 <- count(bings3e1, vars = "Episode")
countbings3e2 <- count(bings3e2, vars = "Episode")
countbings3e3 <- count(bings3e3, vars = "Episode")
countbings3e4 <- count(bings3e4, vars = "Episode")
countbings3e5 <- count(bings3e5, vars = "Episode")
countbings3e6 <- count(bings3e6, vars = "Episode")
countbings3e7 <- count(bings3e7, vars = "Episode")
countbings3e8 <- count(bings3e8, vars = "Episode")
countbings3e9 <- count(bings3e9, vars = "Episode")
countbings3e10 <- count(bings3e10, vars = "Episode")
countbings3e11 <- count(bings3e11, vars = "Episode")
countbings3e12 <- count(bings3e12, vars = "Episode")
countbings3e13 <- count(bings3e13, vars = "Episode")
countbings3e14 <- count(bings3e14, vars = "Episode")
countbings3e15 <- count(bings3e15, vars = "Episode")
countbings3e16 <- count(bings3e16, vars = "Episode")
countbings3e17 <- count(bings3e17, vars = "Episode")
countbings3e18 <- count(bings3e18, vars = "Episode")
## afinn Filter Positive
positiveAs3e1 <- afinns3e1 %>% filter(value >= 0)
positiveAs3e2 <- afinns3e2 %>% filter(value >= 0)
positiveAs3e3 <- afinns3e3 %>% filter(value >= 0)
positiveAs3e4 <- afinns3e4 %>% filter(value >= 0)
positiveAs3e5 <- afinns3e5 %>% filter(value >= 0)
positiveAs3e6 <- afinns3e6 %>% filter(value >= 0)
positiveAs3e7 <- afinns3e7 %>% filter(value >= 0)
positiveAs3e8 <- afinns3e8 %>% filter(value >= 0)
positiveAs3e9 <- afinns3e9 %>% filter(value >= 0)
positiveAs3e10 <- afinns3e10 %>% filter(value >= 0)
positiveAs3e11 <- afinns3e11 %>% filter(value >= 0)
positiveAs3e12 <- afinns3e12 %>% filter(value >= 0)
positiveAs3e13 <- afinns3e13 %>% filter(value >= 0)
positiveAs3e14 <- afinns3e14 %>% filter(value >= 0)
positiveAs3e15 <- afinns3e15 %>% filter(value >= 0)
positiveAs3e16 <- afinns3e16 %>% filter(value >= 0)
positiveAs3e17 <- afinns3e17 %>% filter(value >= 0)
positiveAs3e18 <- afinns3e18 %>% filter(value >= 0)
## bing Filter Positive
positiveBs3e1 <- bings3e1 %>% filter(sentiment == 'positive')
positiveBs3e2 <- bings3e2 %>% filter(sentiment == 'positive')
positiveBs3e3 <- bings3e3 %>% filter(sentiment == 'positive')
positiveBs3e4 <- bings3e4 %>% filter(sentiment == 'positive')
positiveBs3e5 <- bings3e5 %>% filter(sentiment == 'positive')
positiveBs3e6 <- bings3e6 %>% filter(sentiment == 'positive')
positiveBs3e7 <- bings3e7 %>% filter(sentiment == 'positive')
positiveBs3e8 <- bings3e8 %>% filter(sentiment == 'positive')
positiveBs3e9 <- bings3e9 %>% filter(sentiment == 'positive')
positiveBs3e10 <- bings3e10 %>% filter(sentiment == 'positive')
positiveBs3e11 <- bings3e11 %>% filter(sentiment == 'positive')
positiveBs3e12 <- bings3e12 %>% filter(sentiment == 'positive')
positiveBs3e13 <- bings3e13 %>% filter(sentiment == 'positive')
positiveBs3e14 <- bings3e14 %>% filter(sentiment == 'positive')
positiveBs3e15 <- bings3e15 %>% filter(sentiment == 'positive')
positiveBs3e16 <- bings3e16 %>% filter(sentiment == 'positive')
positiveBs3e17 <- bings3e17 %>% filter(sentiment == 'positive')
positiveBs3e18 <- bings3e18 %>% filter(sentiment == 'positive')
## afinn Count Positives
countPAs3e1 <- count(positiveAs3e1, vars = "Episode")
countPAs3e2 <- count(positiveAs3e2, vars = "Episode")
countPAs3e3 <- count(positiveAs3e3, vars = "Episode")
countPAs3e4 <- count(positiveAs3e4, vars = "Episode")
countPAs3e5 <- count(positiveAs3e5, vars = "Episode")
countPAs3e6 <- count(positiveAs3e6, vars = "Episode")
countPAs3e7 <- count(positiveAs3e7, vars = "Episode")
countPAs3e8 <- count(positiveAs3e8, vars = "Episode")
countPAs3e9 <- count(positiveAs3e9, vars = "Episode")
countPAs3e10 <- count(positiveAs3e10, vars = "Episode")
countPAs3e11 <- count(positiveAs3e11, vars = "Episode")
countPAs3e12 <- count(positiveAs3e12, vars = "Episode")
countPAs3e13 <- count(positiveAs3e13, vars = "Episode")
countPAs3e14 <- count(positiveAs3e14, vars = "Episode")
countPAs3e15 <- count(positiveAs3e15, vars = "Episode")
countPAs3e16 <- count(positiveAs3e16, vars = "Episode")
countPAs3e17 <- count(positiveAs3e17, vars = "Episode")
countPAs3e18 <- count(positiveAs3e18, vars = "Episode")
## bing Count Positives
countPBs3e1 <- count(positiveBs3e1, vars = "Episode")
countPBs3e2 <- count(positiveBs3e2, vars = "Episode")
countPBs3e3 <- count(positiveBs3e3, vars = "Episode")
countPBs3e4 <- count(positiveBs3e4, vars = "Episode")
countPBs3e5 <- count(positiveBs3e5, vars = "Episode")
countPBs3e6 <- count(positiveBs3e6, vars = "Episode")
countPBs3e7 <- count(positiveBs3e7, vars = "Episode")
countPBs3e8 <- count(positiveBs3e8, vars = "Episode")
countPBs3e9 <- count(positiveBs3e9, vars = "Episode")
countPBs3e10 <- count(positiveBs3e10, vars = "Episode")
countPBs3e11 <- count(positiveBs3e11, vars = "Episode")
countPBs3e12 <- count(positiveBs3e12, vars = "Episode")
countPBs3e13 <- count(positiveBs3e13, vars = "Episode")
countPBs3e14 <- count(positiveBs3e14, vars = "Episode")
countPBs3e15 <- count(positiveBs3e15, vars = "Episode")
countPBs3e16 <- count(positiveBs3e16, vars = "Episode")
countPBs3e17 <- count(positiveBs3e17, vars = "Episode")
countPBs3e18 <- count(positiveBs3e18, vars = "Episode")
## bing Filter Negative
negativeBs3e1 <- bings3e1 %>% filter(sentiment == 'negative')
negativeBs3e2 <- bings3e2 %>% filter(sentiment == 'negative')
negativeBs3e3 <- bings3e3 %>% filter(sentiment == 'negative')
negativeBs3e4 <- bings3e4 %>% filter(sentiment == 'negative')
negativeBs3e5 <- bings3e5 %>% filter(sentiment == 'negative')
negativeBs3e6 <- bings3e6 %>% filter(sentiment == 'negative')
negativeBs3e7 <- bings3e7 %>% filter(sentiment == 'negative')
negativeBs3e8 <- bings3e8 %>% filter(sentiment == 'negative')
negativeBs3e9 <- bings3e9 %>% filter(sentiment == 'negative')
negativeBs3e10 <- bings3e10 %>% filter(sentiment == 'negative')
negativeBs3e11 <- bings3e11 %>% filter(sentiment == 'negative')
negativeBs3e12 <- bings3e12 %>% filter(sentiment == 'negative')
negativeBs3e13 <- bings3e13 %>% filter(sentiment == 'negative')
negativeBs3e14 <- bings3e14 %>% filter(sentiment == 'negative')
negativeBs3e15 <- bings3e15 %>% filter(sentiment == 'negative')
negativeBs3e16 <- bings3e16 %>% filter(sentiment == 'negative')
negativeBs3e17 <- bings3e17 %>% filter(sentiment == 'negative')
negativeBs3e18 <- bings3e18 %>% filter(sentiment == 'negative')
## afinn Count Negatives
countNAs3e1 <- count(negativeAs3e1, vars = "Episode")
countNAs3e2 <- count(negativeAs3e2, vars = "Episode")
countNAs3e3 <- count(negativeAs3e3, vars = "Episode")
countNAs3e4 <- count(negativeAs3e4, vars = "Episode")
countNAs3e5 <- count(negativeAs3e5, vars = "Episode")
countNAs3e6 <- count(negativeAs3e6, vars = "Episode")
countNAs3e7 <- count(negativeAs3e7, vars = "Episode")
countNAs3e8 <- count(negativeAs3e8, vars = "Episode")
countNAs3e9 <- count(negativeAs3e9, vars = "Episode")
countNAs3e10 <- count(negativeAs3e10, vars = "Episode")
countNAs3e11 <- count(negativeAs3e11, vars = "Episode")
countNAs3e12 <- count(negativeAs3e12, vars = "Episode")
countNAs3e13 <- count(negativeAs3e13, vars = "Episode")
countNAs3e14 <- count(negativeAs3e14, vars = "Episode")
countNAs3e15 <- count(negativeAs3e15, vars = "Episode")
countNAs3e16 <- count(negativeAs3e16, vars = "Episode")
countNAs3e17 <- count(negativeAs3e17, vars = "Episode")
countNAs3e18 <- count(negativeAs3e18, vars = "Episode")
## bing Count Negatives
countNBs3e1 <- count(negativeBs3e1, vars = "Episode")
countNBs3e2 <- count(negativeBs3e2, vars = "Episode")
countNBs3e3 <- count(negativeBs3e3, vars = "Episode")
countNBs3e4 <- count(negativeBs3e4, vars = "Episode")
countNBs3e5 <- count(negativeBs3e5, vars = "Episode")
countNBs3e6 <- count(negativeBs3e6, vars = "Episode")
countNBs3e7 <- count(negativeBs3e7, vars = "Episode")
countNBs3e8 <- count(negativeBs3e8, vars = "Episode")
countNBs3e9 <- count(negativeBs3e9, vars = "Episode")
countNBs3e10 <- count(negativeBs3e10, vars = "Episode")
countNBs3e11 <- count(negativeBs3e11, vars = "Episode")
countNBs3e12 <- count(negativeBs3e12, vars = "Episode")
countNBs3e13 <- count(negativeBs3e13, vars = "Episode")
countNBs3e14 <- count(negativeBs3e14, vars = "Episode")
countNBs3e15 <- count(negativeBs3e15, vars = "Episode")
countNBs3e16 <- count(negativeBs3e16, vars = "Episode")
countNBs3e17 <- count(negativeBs3e17, vars = "Episode")
countNBs3e18 <- count(negativeBs3e18, vars = "Episode")

## Look up loughlin dictionary

# Bing rows
season1 <- bind_rows(s1e1,s1e2,s1e3,s1e4,s1e5,s1e6,s1e7,s1e8)
season2 <- bind_rows(s2e1,s2e2,s2e3,s2e4,s2e5,s2e6,s2e7,s2e8,s2e9,s2e10,s2e11,s2e12,s2e13,s2e14,s2e15,s2e16,s2e17,s2e18,s2e19,s2e20,s2e21,s2e22)
season3 <- bind_rows(s3e1,s3e2,s3e3,s3e4,s3e5,s3e6,s3e7,s3e8,s3e9,s3e10,s3e11,s3e12,s3e13,s3e14,s3e15,s3e16,s3e17,s3e18)


s2ap <- bind_rows(s2e1PosAfinn,s2e2PosAfinn,s2e3PosAfinn,s2e4PosAfinn,s2e5PosAfinn,s2e6PosAfinn,s2e7PosAfinn,s2e8PosAfinn,s2e9PosAfinn,s2e10PosAfinn,s2e11PosAfinn,s2e12PosAfinn,s2e13PosAfinn,s2e14PosAfinn,s2e15PosAfinn,s2e16PosAfinn,s2e17PosAfinn,s2e18PosAfinn,s2e19PosAfinn,s2e20PosAfinn,s2e21PosAfinn,s2e22PosAfinn)
s2an <- bind_rows()

write.csv(s2ap, file = "top-ten/season2/full.csv")
## Src = https://www.youtube.com/watch?v=BqNTcewq0k0
#Word Cloud
library(wordcloud)
library(reshape2)
#Basic Wordcloud
wordCloudS1 <- tibSeason1 %>% with(tibSeason1, !(word =="value")) %>% count(word) %>% with (wordcloud(word, n, max.words = 100))
#Wordcloud group +-
afinns1e1 %>% count(word, value, sort=TRUE) %>% acast(word ~ value, value.var = "n", fill = 0) %>% comparison.cloud(colors = c("#F8766D","#00BFC4"), max.words = 100)

