library(dplyr)
library(tidytext)
library(tidyverse)


## Import Datasets
s1e1 <- read.csv("s1e1-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e2 <- read.csv("s1e2-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e3 <- read.csv("s1e3-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e4 <- read.csv("s1e4-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e5 <- read.csv("s1e5-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e6 <- read.csv("s1e6-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e7 <- read.csv("s1e7-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e8 <- read.csv("s1e8-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)

## create a tibble with the Episode ([,1]) & Words ([,2])
tibs1e1 <- tibble(Episode = s1e1[,1], Words = s1e1[,2])
tibs1e2 <- tibble(Episode = s1e2[,1], Words = s1e2[,2])
tibs1e3 <- tibble(Episode = s1e3[,1], Words = s1e3[,2])
tibs1e4 <- tibble(Episode = s1e4[,1], Words = s1e4[,2])
tibs1e5 <- tibble(Episode = s1e5[,1], Words = s1e5[,2])
tibs1e6 <- tibble(Episode = s1e6[,1], Words = s1e6[,2])
tibs1e7 <- tibble(Episode = s1e7[,1], Words = s1e7[,2])
tibs1e8 <- tibble(Episode = s1e8[,1], Words = s1e8[,2])

## Use Inner_Join with Affin
affins1e1 <- tibs1e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e2 <- tibs1e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e3 <- tibs1e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e4 <- tibs1e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e5 <- tibs1e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e6 <- tibs1e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e7 <- tibs1e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e8 <- tibs1e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))

## Count
counts1e1 <- count(affins1e1, vars = "Episode")
counts1e2 <- count(affins1e2, vars = "Episode")
counts1e3 <- count(affins1e3, vars = "Episode")
counts1e4 <- count(affins1e4, vars = "Episode")
counts1e5 <- count(affins1e5, vars = "Episode")
counts1e6 <- count(affins1e6, vars = "Episode")
counts1e7 <- count(affins1e7, vars = "Episode")
counts1e8 <- count(affins1e8, vars = "Episode")

## Filter Positive
positives1e1 <- affins1e1 %>% filter(value >= 0)
positives1e2 <- affins1e2 %>% filter(value >= 0)
positives1e3 <- affins1e3 %>% filter(value >= 0)
positives1e4 <- affins1e4 %>% filter(value >= 0)
positives1e5 <- affins1e5 %>% filter(value >= 0)
positives1e6 <- affins1e6 %>% filter(value >= 0)
positives1e7 <- affins1e7 %>% filter(value >= 0)
positives1e8 <- affins1e8 %>% filter(value >= 0)
## Filter Negative

## Season 2
s2e1 <- read.csv("s2e1-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e2 <- read.csv("s2e2-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e3 <- read.csv("s2e3-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e4 <- read.csv("s2e4-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e5 <- read.csv("s2e5-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e6 <- read.csv("s2e6-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e7 <- read.csv("s2e7-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e8 <- read.csv("s2e8-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e9 <- read.csv("s2e9-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e10 <- read.csv("s2e10-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e11 <- read.csv("s2e11-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e12 <- read.csv("s2e12-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e13 <- read.csv("s2e13-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e14 <- read.csv("s2e14-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e15 <- read.csv("s2e15-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e16 <- read.csv("s2e16-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e17 <- read.csv("s2e17-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e18 <- read.csv("s2e18-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e19 <- read.csv("s2e19-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e20 <- read.csv("s2e20-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e21 <- read.csv("s2e21-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s2e22 <- read.csv("s2e22-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)

## create a tibble with the Episode ([,1]) & Words ([,2])
tibs2e1 <- tibble(Episode = s2e1[,1], Words = s2e1[,2])
tibs2e2 <- tibble(Episode = s2e2[,1], Words = s2e2[,2])
tibs2e3 <- tibble(Episode = s2e3[,1], Words = s2e3[,2])
tibs2e4 <- tibble(Episode = s2e4[,1], Words = s2e4[,2])
tibs2e5 <- tibble(Episode = s2e5[,1], Words = s2e5[,2])
tibs2e6 <- tibble(Episode = s2e6[,1], Words = s2e6[,2])
tibs2e7 <- tibble(Episode = s2e7[,1], Words = s2e7[,2])
tibs2e8 <- tibble(Episode = s2e8[,1], Words = s2e8[,2])
tibs2e9 <- tibble(Episode = s2e9[,1], Words = s2e9[,2])
tibs2e10 <- tibble(Episode = s2e10[,1], Words = s2e10[,2])
tibs2e11 <- tibble(Episode = s2e11[,1], Words = s2e11[,2])
tibs2e12 <- tibble(Episode = s2e12[,1], Words = s2e12[,2])
tibs2e13 <- tibble(Episode = s2e13[,1], Words = s2e13[,2])
tibs2e14 <- tibble(Episode = s2e14[,1], Words = s2e14[,2])
tibs2e15 <- tibble(Episode = s2e15[,1], Words = s2e15[,2])
tibs2e16 <- tibble(Episode = s2e16[,1], Words = s2e16[,2])
tibs2e17 <- tibble(Episode = s2e17[,1], Words = s2e17[,2])
tibs2e18 <- tibble(Episode = s2e18[,1], Words = s2e18[,2])
tibs2e19 <- tibble(Episode = s2e19[,1], Words = s2e19[,2])
tibs2e20 <- tibble(Episode = s2e20[,1], Words = s2e20[,2])
tibs2e21 <- tibble(Episode = s2e21[,1], Words = s2e21[,2])
tibs2e22 <- tibble(Episode = s2e22[,1], Words = s2e22[,2])

## Use Inner_Join with Affin
affins2e1 <- tibs2e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e2 <- tibs2e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e3 <- tibs2e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e4 <- tibs2e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e5 <- tibs2e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e6 <- tibs2e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e7 <- tibs2e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e8 <- tibs2e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e9 <- tibs2e9 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e10 <- tibs2e10 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e11 <- tibs2e11 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e12 <- tibs2e12 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e13 <- tibs2e13 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e14 <- tibs2e14 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e15 <- tibs2e15 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e16 <- tibs2e16 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e17 <- tibs2e17 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e18 <- tibs2e18 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e19 <- tibs2e19 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e20 <- tibs2e20 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e21 <- tibs2e21 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins2e22 <- tibs2e22 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))

## Count
counts2e1 <- count(affins2e1, vars = "Episode")
counts2e2 <- count(affins2e2, vars = "Episode")
counts2e3 <- count(affins2e3, vars = "Episode")
counts2e4 <- count(affins2e4, vars = "Episode")
counts2e5 <- count(affins2e5, vars = "Episode")
counts2e6 <- count(affins2e6, vars = "Episode")
counts2e7 <- count(affins2e7, vars = "Episode")
counts2e8 <- count(affins2e8, vars = "Episode")
counts2e9 <- count(affins2e9, vars = "Episode")
counts2e10 <- count(affins2e10, vars = "Episode")
counts2e11 <- count(affins2e11, vars = "Episode")
counts2e12 <- count(affins2e12, vars = "Episode")
counts2e13 <- count(affins2e13, vars = "Episode")
counts2e14 <- count(affins2e14, vars = "Episode")
counts2e15 <- count(affins2e15, vars = "Episode")
counts2e16 <- count(affins2e16, vars = "Episode")
counts2e17 <- count(affins2e17, vars = "Episode")
counts2e18 <- count(affins2e18, vars = "Episode")
counts2e19 <- count(affins2e19, vars = "Episode")
counts2e20 <- count(affins2e20, vars = "Episode")
counts2e21 <- count(affins2e21, vars = "Episode")
counts2e22 <- count(affins2e22, vars = "Episode")