library(dplyr)
library(tidytext)


## Import Datasets
s1e1 <- read.csv("s1e1-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e2 <- read.csv("s1e2-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e3 <- read.csv("s1e3-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e4 <- read.csv("s1e4-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e5 <- read.csv("s1e5-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e6 <- read.csv("s1e6-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e7 <- read.csv("s1e7-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)
s1e8 <- read.csv("s1e8-mod.txt", sep=",", header=TRUE, stringsAsFactors = FALSE)

## create a tibble with the Episode ([,1]) & Words ([,2])
tibs1e1 <- tibble(Episode = s1e1[,1], Words = s1e1[,2])
tibs1e2 <- tibble(Episode = s1e2[,1], Words = s1e2[,2])
tibs1e3 <- tibble(Episode = s1e3[,1], Words = s1e3[,2])
tibs1e4 <- tibble(Episode = s1e4[,1], Words = s1e4[,2])
tibs1e5 <- tibble(Episode = s1e5[,1], Words = s1e5[,2])
tibs1e6 <- tibble(Episode = s1e6[,1], Words = s1e6[,2])
tibs1e7 <- tibble(Episode = s1e7[,1], Words = s1e7[,2])
tibs1e8 <- tibble(Episode = s1e8[,1], Words = s1e8[,2])

## Use Inner_Join with Affin
affins1e1 <- tibs1e1 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e2 <- tibs1e2 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e3 <- tibs1e3 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e4 <- tibs1e4 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e5 <- tibs1e5 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e6 <- tibs1e6 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e7 <- tibs1e7 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))
affins1e8 <- tibs1e8 %>% unnest_tokens(word, Words) %>% inner_join(get_sentiments("afinn"))

## Count
counts1e1 <- count(affins1e1, vars = "Episode")
counts1e2 <- count(affins1e2, vars = "Episode")
counts1e3 <- count(affins1e3, vars = "Episode")
counts1e4 <- count(affins1e4, vars = "Episode")
counts1e5 <- count(affins1e5, vars = "Episode")
counts1e6 <- count(affins1e6, vars = "Episode")
counts1e7 <- count(affins1e7, vars = "Episode")
counts1e8 <- count(affins1e8, vars = "Episode")


## Season 2
s2e1 <- read_csv("s2e1.txt", col_names = FALSE)
s2e2 <- read_csv("s2e2.txt", col_names = FALSE)
s2e3 <- read_csv("s2e3.txt", col_names = FALSE)
s2e4 <- read_csv("s2e4.txt", col_names = FALSE)
s2e5 <- read_csv("s2e5.txt", col_names = FALSE)
s2e6 <- read_csv("s2e6.txt", col_names = FALSE)
s2e7 <- read_csv("s2e7.txt", col_names = FALSE)
s2e8 <- read_csv("s2e8.txt", col_names = FALSE)
s2e9 <- read_csv("s2e9.txt", col_names = FALSE)
s2e10 <- read_csv("s2e10.txt", col_names = FALSE)
s2e11 <- read_csv("s2e11.txt", col_names = FALSE)
s2e12 <- read_csv("s2e12.txt", col_names = FALSE)
s2e13 <- read_csv("s2e13.txt", col_names = FALSE)
s2e14 <- read_csv("s2e14.txt", col_names = FALSE)
s2e15 <- read_csv("s2e15.txt", col_names = FALSE)
s2e16 <- read_csv("s2e16.txt", col_names = FALSE)
s2e17 <- read_csv("s2e17.txt", col_names = FALSE)
s2e18 <- read_csv("s2e18.txt", col_names = FALSE)
s2e19 <- read_csv("s2e19.txt", col_names = FALSE)
s2e20 <- read_csv("s2e20.txt", col_names = FALSE)
s2e21 <- read_csv("s2e21.txt", col_names = FALSE)
s2e22 <- read_csv("s2e22.txt", col_names = FALSE)


## Same them out
write.csv(s2e1, file = "s2e1-mod.txt")
write.csv(s2e2, file = "s2e2-mod.txt")
write.csv(s2e3, file = "s2e3-mod.txt")
write.csv(s2e4, file = "s2e4-mod.txt")
write.csv(s2e5, file = "s2e5-mod.txt")
write.csv(s2e6, file = "s2e6-mod.txt")
write.csv(s2e7, file = "s2e7-mod.txt")
write.csv(s2e8, file = "s2e8-mod.txt")
write.csv(s2e9, file = "s2e9-mod.txt")
write.csv(s2e10, file = "s2e10-mod.txt")
write.csv(s2e11, file = "s2e11-mod.txt")
write.csv(s2e12, file = "s2e12-mod.txt")
write.csv(s2e13, file = "s2e13-mod.txt")
write.csv(s2e14, file = "s2e14-mod.txt")
write.csv(s2e15, file = "s2e15-mod.txt")
write.csv(s2e16, file = "s2e16-mod.txt")
write.csv(s2e17, file = "s2e17-mod.txt")
write.csv(s2e18, file = "s2e18-mod.txt")
write.csv(s2e19, file = "s2e19-mod.txt")
write.csv(s2e20, file = "s2e20-mod.txt")
write.csv(s2e21, file = "s2e21-mod.txt")
write.csv(s2e22, file = "s2e22-mod.txt")